### ISSUE TITLE
implementation of barcode whitelist

### ISSUE THREAD

**Issue by baracus37** [Hoohm/CITE-seq-Count#1]
Hi,

I would like to propose implementing the use of a barcode whitelist for Cite-seq-count. As of now the output generated contains TAG counts for all encountered Cell barcodes and not just for those that have been identified as cell associated. The process of TAG counting could potentially be accelerated by only counting TAGs for cell associated barcodes and it would reduce the dimensions and file size of the output table, which again would improve downstream analysis. 
For 10X one could just the barcodes.tsv from "/outs/filtered_gene_bc_matrices/" as whitelist.

Best,

Tobias

**Comment by Hoohm** [comment]
I'ts now proposed as an option:

`--whitelist or -wl`

It shuold be a csv file of barcodes with no headers.

**Comment by baracus37** [comment]
I have just tested the new version of the script and it works just as intended. Thanks a lot. The output is now much smaller and only contains valuable information.
