### ISSUE TITLE
Top unknown barcodes?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#10]
Hello,

So far as I can see with CITE-seq-Count, one provides a table of expected barcodes.  The final report includes rows for each barcode, bad_struct, and no_match.  Is there any way to make it report the frequency of barcodes in the no_match category?  For example, when you run bcl2fastq, that report lists top unknown barcodes.  This is a nice check in case the barcodes actually used dont line up w/ what's expected.  

thanks

**Comment by bbimber** [comment]
This isnt fully ready, but I was playing around w/ a fork that adds the option to write the unknown tags to a separate file:

https://github.com/bbimber/CITE-seq-Count/tree/unknown-barcodes

If you'd consider something like this as an option in your tool, I could clean that up and put in a PR.

**Comment by Hoohm** [comment]
Hello @bbimber and thanks for the idea.

I've looked up your code.
Code looks clear and the idea might be interesting to some.
Sure, clean it up and PR, I'll gladly add the option :+1: 

Thanks for the contribution. :)
