### ISSUE TITLE
TotalSeqB run selects other cells than TotalSeqA run

### ISSUE THREAD

**Issue by Erinke89** [Hoohm/CITE-seq-Count#100]
Dear @Hoohm ,

Thank you for developing this tool!
I use it for a sample with 2 TotalSeqA antibodies and 2 TotalSeqB antibodies, run with 10x V3. For running CITE-seq-Count I'm using a cell barcode whitelist based on QC on the gene expression of these cells. When I run the TSA library through CSC, the results look very good. However, when I run the TSB library, almost all cells have a count of zero... Of course, I used -trim 10 to account for the different sequence in the TSA vs TSB, but other than that I kept the options the same. 
The weird thing is, when I'm running the TSB library without a whitelist, there are cells in there that have high counts for the tags but they have totally different barcodes than the cells in my whitelist (overlap of 3 cells...). This doesn't make sense to me, and also, when I run TSB through Cellranger, the high counts _are_ found in the cells in the whitelist.

So it seems I'm making a mistake with the assignment of the tag counts to the cell barcodes. I've played with the correction thresholds but this didn't improve the result. Does my result have something to do with the "mapping between RNA cell barcodes and Protein cell barcodes"  that you mention shortly in your guidelines? I'm afraid I don't really understand what you mean with that, and what I should do to be able to analyse this data. Would you please elaborate?

Any help would be greatly appreciated, thank you so much in advance!

Run report of my TSB run:
CITE-seq-Count Version: 1.4.3                                                                                                                                      Reads processed: 53379566                                                                                                                                          Percentage mapped: 93                                                                                                                                              Percentage unmapped: 7                                                                                                                                             Uncorrected cells: 0                                                                                                                                               Correction:                                                                                                                                                                Cell barcodes collapsing threshold: 0                                                                                                                              Cell barcodes corrected: 0                                                                                                                                         UMI collapsing threshold: 1                                                                                                                                        UMIs corrected: 56                                                                                                                                         Run parameters:                                                                                                                                                            Read1_paths: data.dir/729726_GX89_S30_L002_001.fastq.1.gz                                                                                                          Read2_paths: data.dir/729726_GX89_S30_L002_001.fastq.2.gz                                                                                                          Cell barcode:                                                                                                                                                              First position: 1                                                                                                                                                  Last position: 16                                                                                                                                          UMI barcode:                                                                                                                                                               First position: 17                                                                                                                                                 Last position: 28                                                                                                                                          Expected cells: 12000                                                                                                                                              Tags max errors: 2                                                                                                                                                 Start trim: 10

**Comment by Hoohm** [comment]
Hi @Erinke89 
the problem with V3 is that the cell barcode used for the RNA data is not the same cell barcode for the protein data.

What you see is expected, the data you processed is there, you just have to map it to the right RNA barcodes. I'm gonna post some code to help you out tomorrow with this.

**Comment by Erinke89** [comment]
Thank you for explaining! I didn't expect 10x to do that, that seems quite prone to confusion.
It would be super if you can help me (and others) to map the TotalSeqB counts to the correct RNA counts!

**Comment by zqfang** [comment]
Any progress here? I have the same problem with TotalSeqB counts.  I only got 14 overlap cell barcodes from cellranger output and cite-seq-count ouput. @Hoohm 

Is there any quick solution here?

**Comment by Erinke89** [comment]
Hi @zqfang, the quick solution would be to use cellranger count instead of CITEseq count... For Totalseq B this is supported and for me it seems to work okay. (For TotalseqA this is a different story). See https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/feature-bc-analysis

**Comment by zqfang** [comment]
Thanks @Erinke89, that's really helps

**Comment by Hoohm** [comment]
Hello @Erinke89 
sorry for the long waiting time, here is the short code I promised you

https://gist.github.com/Hoohm/edf05b544105cd3f396d6e8c5dd66b22

It awaits two things. The 3M whitelist from 10x (https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/translation/3M-february-2018.txt.gz) and a filtered RNA cell barcode whitelist that you got from cellranger.

The mapping whitelist given at the end can be then used for CITE-seq-Count.

**Comment by Erinke89** [comment]
Hello @Hoohm 
Thank you for the code!! I just tested it and now it works fully as expected, the counts seem to be assigned to the correct cells! 
Thank you for your help!

**Comment by lshepard2154** [comment]
Quick question in regards to this issue for **_clarification_**:

The issue described here with V3 in regards to barcode differences is only for TotalSeqB correct? Cell barcodes for TotalSeqA should still match between the CITE-seq files and the RNA correct?

That seems the reasonable conclusion from reading this thread given the description of the issue, but wanted to double check as V3 can be used in both. Thanks!

**Comment by Erinke89** [comment]
Hi @lshepard2154 , I'm just posting this here, maybe it can clarify some things for you and others googling similar questions. This is how 10x explained to me after a lot of emailing back & forth:

"Regarding your observation that the barcodes do not overlap between GEX+Ab and Antibody only runs: I think you might be observing this only for TotalSeqA datasets. The reason is that each 3’ GEX Gel Bead contains two variants of the embedded oligos, one for capturing gene expression data, and another for Feature Barcoding technology. For example if the GEX barcode sequence is: AAACCCAAGAAACACT, the Feature Barcoding barcode sequence is: AAACCCATCAAACACT.

The mRNa is captured using polydT and get one variant of the 10x barcode. TotalSeqB and C are captured using one of the Capture Sequences (1 or 2) and they have the other variant of the 10x barcode. On the other hand, if you are using TotalSeqA, they are captured using polydT and so they get the same variant of the 10x barcode as the mRNA.

Cellranger has no way of determining which panel of antibodies was used. It only has the barcode information which is generated post sequencing. Cell Ranger translates the "Antibody Capture" barcodes back to the GEX barcodes when reporting in the matrices. 

So if you were to run TotalSeqB (officially supported) or TotalSeqC in antibody only mode, Cell Ranger would report the translated barcodes and they would match the GEX barcodes. 

However, if you are running Antibody only pipeline on TotalSeqA data, these barcodes are already in GEX variant and so Cell Ranger ends up converting (translating) them to the other variant. Unfortunately, at this time, Cell Ranger does not have a way to avoid this conversion."

**Comment by lshepard2154** [comment]
@Erinke89 thanks for the post. In other words (shorter version in my understanding): TotalSeqA (CITE-seq/antibodies) uses the same barcodes (even in V3 version) as the RNA-seq run, however since they are the same, CellRanger doesn't support. Thus one must use CITE-seq-count. 

TotalSeqB/C, uses the variants sequence described and CellRanger supports this conversion. Standard use of Cite-seq-count would not be suitable, however with the code that @Hoohm posted above (https://gist.github.com/Hoohm/edf05b544105cd3f396d6e8c5dd66b22), then it's suitable. _I think this covers the current consensus

**Comment by f0ng1203** [comment]
Hi @Hoohm 

I am very new to programming. Currently, I am running 10X scRNA-seq using TotalSeq C antibody as hashtags. I am aware that you have written a code for converting TotalSeqB. May I know how do I run this python code? Secondly, how do I get the filtered RNA cell barcode whitelist from CellRanger?

Thanks in advance.

**Comment by naila53** [comment]
thanks @Erinke89 this is very helpful. I'm trying to get a test run of Citeseq Count with 10x totalseqB dataset. when i look at the Read2 fastq files for the surface proteins the read lenght is 91. this is also shown in the protocol
<img width="819" alt="Screen Shot 2021-06-19 at 6 49 06 PM" src="https://user-images.githubusercontent.com/56326205/122646196-07d50080-d12f-11eb-96d0-05ee42c0c61b.png">

 you specified a -trim of 10. However, it's not clear to me why the read lenght is this long? it should be N9+feature barcode+N10 which is up to 35 bases according to this refrence
https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_protein_v3/pbmc_1k_protein_v3_feature_ref.csv
