### ISSUE TITLE
cell barcode  Corrected and number of UMI corrected vary a lot for each samples

### ISSUE THREAD

**Issue by YunZheHuang** [Hoohm/CITE-seq-Count#101]
Hello,
I just find that the cell barcode corrected and number of UMIs corrected in the report for each sample are different. for some sample, Cell barcodes corrected is around 20000 while some sample is around 40000. For number of UMI corrected, some sample is around  600000 while some cells around 200000 and some around 1370199. All the parameters used in the CITE-seq-Count command  is the same for these sample and what causes these differences? Thank you!

**Comment by Hoohm** [comment]
Hello @YunZheHuang 
cell barcode and umi correction depend on a lot of different parameter.
Sequencing errors, number of real cells in your sample, length of cell barcode and umis, using a whitelist or not, etc...

You will never have the same number across different samples. Not sure if this answers your question.
