### ISSUE TITLE
umi-correction question

### ISSUE THREAD

**Issue by lshepard2154** [Hoohm/CITE-seq-Count#102]
Hello Patrick,

I am trying to find some additional information regarding UMI correction. Is the theory/purpose of this to simply correct the UMIs for sequencing errors where the default value for this correction corresponds to `--umi_collapsing_dist 2`?

Just wondering what is the best practice here since (to correct or to not correct with `--no_umi_correction`) since I am not finding a lot online about the purpose of this correction.

Thanks!

**Comment by Hoohm** [comment]
Hello @lshepard2154 
There is not a clear consus yet on how to correct UMI. Multiple variables are involved in this process such as sequencing quality, UMI diversity, UMI "production" at the molecular level.

I suggest you read [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5340976/) about the subject it might help you for a specific scenario.

For CSC, I use a default of 2 based on data I was working with.

I also double checked influence of UMI counts later on in Seurat for doublet detection and Tag attribution to cells, clustering, etc...

The differences between 1 or 2 really low and don't have a big influence on the output.

I hope this helps, let me know if that helped.
