### ISSUE TITLE
How is percentage unmapped calculated?

### ISSUE THREAD

**Issue by gitbuckley** [Hoohm/CITE-seq-Count#104]
My run_report.yaml indicates:

Reads processed: 84295918
Percentage mapped: 82
Percentage unmapped: 18

However, when I look at the results in the read_count directory, there are only 22% of the total reads processed present. I assume the others 78% of processed reads were filtered because of the cell barcode whitelist. Furthermore, 40% of the reads that made it through the cell barcode whitelist filter were labeled as unmapped. So I'm wondering how percentage unmapped is calculated? Much thanks!

**Comment by Hoohm** [comment]
Hello @gitbuckley and sorry for the very very late response. It seems that I didn't comp my issues well enough.

The mapping rate is not linked to cell barcodes at all. It's based on all reads like a "bulk" data if you wish.

The output is of course based on the number of cells asked for or the whitelist.

Let me know if you need anything else.
