### ISSUE TITLE
Downstream processing output of HTO counts from CITE-SEQ 

### ISSUE THREAD

**Issue by deevdevil88** [Hoohm/CITE-seq-Count#107]
Hi,
I have a really simple question and perhaps i am missing the obvious. I have run Cite-seq on my HTO fastqs from 10x and the output mapped 88% reads to HTO and 12% were unmapped. Now in the umi count output i essentially have 7 features (6 antibody tags + unmapped). On using this output downstream in Seurat, when i am de-multiplexing my samples, i should include the un-mapped as a feature as well? Logically it makes sense to do that, as it helps to better identify doublets and remove cells which have unmapped reads based on HTO counts. But as i am identifying lot more doublets this way, i wanted to confirm if this is ok.

Any help will be appreciated.

Best,
Devika

**Comment by Hoohm** [comment]
Hello @deevdevil88 
If I remember correctly, the function to label cells based on antibodies and find doublets in Seurat is not taking the unmapped umis into account.

By default, I would recommend to not use the unmapped umis.

**Comment by deevdevil88** [comment]
Hello @Hoohm 
By default, i think Seurat does include the Unmapped unis into classifying doublets, as some cells have a second signal for the unmapped the umis and have been classified as doublets.

So  you would remove the rows of unmapped of umis in the HTO_count matrix and then create the seurat object?

Best,
Devika

**Comment by Hoohm** [comment]
I would take them out. The latest vignette also doesn't use them.
