### ISSUE TITLE
Is there a maximum number of tags cite-seq-count can look for?

### ISSUE THREAD

**Issue by AbbiEdwards** [Hoohm/CITE-seq-Count#111]
I have a ECCITE-seq dataset with 416 tags but when I run cite-seq-count the output is only for 399 tags plus unmapped, am I hitting a maximum here or are these tags not there for another reason?

**Comment by Hoohm** [comment]
Hello @AbbiEdwards,

there is not limit of number of tags that can be mapped.

This just means that those ~20 tags have not been found in your data.

**Comment by AbbiEdwards** [comment]
Thanks!
