### ISSUE TITLE
HTO returning no zero-count cells?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#114]
Hello,

I dont think this is a CITE-seq-count bug per se, but I thought I'd post this in case you have any relevant experience or debugging thoughts.  I have a cell hashing library in with 4 HTOs.  When I run CITE_seq count, 3/4 have a 'normal' distribution of counts.  One of these has at least 1 count in every single cell, with the max counts much higher than the others.  We had to do a lot of PCR to get this HTO library to work, and there are technical reasons why this is probably just bad input.  However, I'd like to see if there are technical solutions (for example, barcode swapping tools), or other QC that I might be able to use to see if reads are being miscalled.  Have you ever experienced problem libraries like this and do you have suggestions?

Note: I'm going to try iterations modifying editDistance and potentially the UMI collapsing params.  I do not see options to make cite-seq-count export any kind of summary or debugging information, but this might be useful if possible.

Thanks,
Ben

**Comment by Hoohm** [comment]
Hello @bbimber,
CSC does not have such a feature for now but you are the second person to request something similar so maybe this will see the light of day. Although, development is slow, so I can't promise you something in a timely manner. If you have some free bandwidth and want to take a crack at it, any help is welcome.

**Comment by Hoohm** [comment]
I'm currently working on the `swith_mod` branch to help our another user. I'm swapping the tag and the UMI string in the results dict. Maybe this could help debug your problem.
