### ISSUE TITLE
No signal from 2/15 CITE-seq antibodies

### ISSUE THREAD

**Issue by rodgson543** [Hoohm/CITE-seq-Count#116]
Hi there,

I was wondering if you had any advice on anything to try for a problem with signal from 2 of my CITE-seq antibodies: 

I have just had the data back from a 10X genomics project, where 6 samples of murine T cells were multiplexed with HashTags, then stained together with 15 CITE-Seq antibodies. 4/6 samples had 10% CD45.1/CD45.1 or CD45.1/CD45.2 spiked in population to act as an internal control, the rest of the sample is CD45.2+/CD45.2+. After de-multiplexing with the HashTags, I had been planning on using CITE-Seq anti-CD45.1 and anti-CD45.2 to identify the spike populations. However, I can't seem to get a signal with them to pull out the populations when using Seurat v3.0 packages. 

**My troubleshooting so far:**
Before sequencing, I confirmed the spike population ratios using flow cytometry, using the same antibody clones for flow as with cite-seq for anti-CD45 isoforms. 
I have also previously used the same clones of anti-CD45.1 and CD45-2 antibodies in combination with the same clone anti-CD45 that is used in the HashTag mixture for mass cytometry - with no problems and clear staining. This data, along with logic that the epitopes shouldn't result in competition gave us confidence that we could use these antibodies for further demultiplexing.

So far, I have tried different methods of normalisation for the ADT CITE-Seq data: neither LogNormalize or CLR normalisation (or just looking at raw counts) have managed to pull out the correct populations by looking at FeatureScatter plots or other visualisation methods. 

Have you got any ideas of whether to try anything else? I don't know if anyone's had similar problems with CITE-Seq antibodies not showing signal and how to troubleshoot this?

Thanks a lot in advance,
Rose

**Comment by Hoohm** [comment]
Hello @rodgson543 

How does the signal of the antiCD45.1 and antiCD45.2 signal look like overall?

Are you running all the antibodies + the two anti45 ones together when running CSC?

Do you have separate libraries for those tages or all in one?

**Comment by rodgson543** [comment]
Hi Hoohm, thanks for your reply and apologies for my slow one!
I had 15 ADT antibodies in totalseq library A and 6 hashtag antibodies in totalseq library B. I have checked the barcodes are correct. For processing/normalisation I have been running all the ADT antibodies together. 

Here are what the raw counts look like for the ADT anti-CD45-1 and anti-CD45-2 compared to anti-CD4.

<img width="393" alt="Screenshot 2020-03-15 at 13 45 25" src="https://user-images.githubusercontent.com/59958085/76702658-4e81b280-66c3-11ea-9f8d-248d349b9b86.png">

**Comment by Hoohm** [comment]
Ok, I would try to normalize the ADT and hashing signal separatly.

Make two separate assays in the seurat object and check if you get something better there.

**Comment by rodgson543** [comment]
I tried normalising the ADT antibodies separately from the hashtag ones and got this result: 
By CLR normalisation:
![image](https://user-images.githubusercontent.com/59958085/76703020-319aae80-66c6-11ea-94b1-63da42a6475b.png)

By log normalisation:
![image](https://user-images.githubusercontent.com/59958085/76703045-4e36e680-66c6-11ea-96b5-60fe073acb79.png)

I thought the log normalised data looked promising but hashtagged samples 3 and 6 shouldn't contain show any CD45-1 expression.

**Comment by Hoohm** [comment]
Is this 10x v3 data?

**Comment by rodgson543** [comment]
Yes it is

**Comment by Hoohm** [comment]
That's the problem.

You need to map the cell barcodes.

Here is a script to help out: https://gist.github.com/Hoohm/edf05b544105cd3f396d6e8c5dd66b22

And here is the explanation: https://hoohm.github.io/CITE-seq-Count/Guidelines/#10xv3

**Comment by Hoohm** [comment]
Hello @rodgson543 did the fix help or not at all?

**Comment by rodgson543** [comment]
Hi Hoohm,

Thanks for following up, no this was already done. I've looking into it further and done some follow up experiments and we're sure the antibodies anti-CD45.1 and anti-CD45.2 just haven't worked. Fortunately the rest have though, so still have some nice data to use!

Thanks so much for all your help and advice, I really appreciate it. 
Best wishes,
Rose

**Comment by Hoohm** [comment]
Happy to see that some have worked properly.
I'm closing this, for now, let me know if you need anything else.
