### ISSUE TITLE
Question about using CITE seq for different Ab barcode design

### ISSUE THREAD

**Issue by dwkarjosukarso** [Hoohm/CITE-seq-Count#119]
Hi, 
it is not necessarily an issue, but I am interested in using CITE-seq to analyse my data. However, I am not sure how I should use it, since my Ab-barcodes design is a bit different.

it is 
19 nt PCR handle - 10 nt Ab Barcode - 8 nt UMI - Stagger (1-16nt) - 8 nt UMI - 21 nt poly A

How shall I specify the locations of the 2 UMI parts?

Thank you.

Best,
Dyah

**Comment by Hoohm** [comment]
Hey @dwkarjosukarso 
it would depend on how those parts are distributed on the reads.

R1 input is for the cell barcode and the UMI
R2 input is for the antibody barcode tag

Both inputs have different options available. So, if all your parts are spread out as mentioned above, you will have no problem using CSC. If not, then you have to do some restructuring of the files beforehand.

**Comment by dwkarjosukarso** [comment]
Hi @Hoohm 
thanks for your reply. 
In our experiment we have
R1 antibody barcode tag (structure: see previous message)
R2 cell barcode and UMI

Thus, to run CITEseq I swapped the R1 and R2 to match CITEseq requirements.
We are using plate-based Celseq2 format, so I specified the cell barcode and UMI position, and gave a cell barcode whitelist. The rest is default settings

We detected 80 Ab features, whereas the experiment only used 71 Ab. Do you have any suggestion on what to improve to get accurate number?

**Comment by Hoohm** [comment]
How did you find 9 features that you did not provide?

**Comment by dwkarjosukarso** [comment]
Feature counts.

In the Ab barcodes list, I provided 10 cell hashing barcodes that we have. Cell hashing was not performed in this experiment, so I was expecting 0 counts.

**Comment by Hoohm** [comment]
Hey @dwkarjosukarso 
just so that I can tell you with certainty what's needed, can you write your read/barcode scheme like this?

R1.fastq.gz
CCCCCCCCUUUUUUUUUU
R2.fastq.gz
TTTTTTTTTTTTNNNNNNNNNNNNNNNNNN

This scheme would be an example where R1 holds 8 cell barcodes and 10 UMI
R2 would hold 12 TAG bases and 18 unknown or irrelevant.

**Comment by dwkarjosukarso** [comment]
Hi @Hoohm 

The read/barcode scheme is below:
R1.fastq.gz
CCCCCCCCUUUUUUUU
R2.fastq.gz
TTTTTTTTTTN[53]

R1: 8 cell barcode and 8 UMI
R2: 10 TAG and 53 of irrelevant (8 UMI, 1-16 Stagger, 8 UMI, 18 poly A)

**Comment by Hoohm** [comment]
So if you give: `-bcf 1 -bcl 8 -umif 9 -umil 16` it doesn't work?

**Comment by dwkarjosukarso** [comment]
It works, but somehow I also detected other antibodies that were not used in the panel during experiment, but I included in the analysis. E.g. the total panel is 80 Ab, but only 70 used in the actual experiment. During analysis I included the extra 10 Ab anyway to see how specific the Ab barcode detection and I still detect cells with 80 Ab even with settings that doesn't allow mismatch (max error 0, umi_collapse 0, cell_barcode_collapse 0. Shall I just exclude those cells from the analysis?

**Comment by Hoohm** [comment]
I'm guessing those numbers are pretty low. If not, then it means something might be wrong with the protocol or you have "transfer" from an experiment to another.
Could also be a sequencing issue, if you are sequencing all together but you get index hoping: https://www.illumina.com/science/education/minimizing-index-hopping.html

**Comment by Hoohm** [comment]
Closing this for now. Let me know if you need more help.
