### ISSUE TITLE
cell hashing?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#12]
this is a very useful tool to create counts per tag.  for CITE-seq that's all that's needed.  for cell hashing, one would want to make a determination per cell, using some algorithm to identify doublets and make a sample call per cell.  do you have established code to do this?   thanks.

**Comment by Hoohm** [comment]
Glad it help :)

I strongly suggest you take a look at a this [vignette](https://satijalab.org/seurat/hashing_vignette.html)

You can use this as a start to look for doublets and empty cells.
