### ISSUE TITLE
Cite-seq-count vs. 10x's count software?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#127]
Hello,

As you might know 10x has released feature barcoding and software to parse a count matrix from data (https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/feature-bc-analysis).  Have you looked into this, and do you know if you or anyone has done any kind of head-to-head comparison with them?  Is there any reason to think one tool might be better than another?

Thanks,
Ben

**Comment by Hoohm** [comment]
Hello @bbimber,
I haven't done a comparison myself but I stumbled upon this paper who did:
https://www.biorxiv.org/content/10.1101/2020.06.15.153080v1.full.pdf

Overall, I think CITE-seq-Count seems to do well against cellranger and I have to say, I'm pretty happy and proud it stands up pretty well against newest softwares.

There is still the performance issue with high number of reads that I'm trying to fix.

**Comment by Hoohm** [comment]
Closing this. 1.5.0 is almost done!!!
