### ISSUE TITLE
CITE-seq-Count is working without HTO (antibody barcode) 

### ISSUE THREAD

**Issue by shannjiang** [Hoohm/CITE-seq-Count#129]
Hi,

I am using CITE-seq-Count on our CITE-seq fastq files. I am not sure if this is an issue or not: I checked our HTO_R2.fastq file, there are no HTO, or antibody barcode, at the beginning of the reads in HTO_R2.fastq file, but CITE-seq-Count is totally working fine...

There are two fastq files for each individual sample in our study. One is named as HTO_R1/2.fastq, the other one is cDNA_R1/2.fastq. Weirdly, I found these HTOs at the beginning of the reads in both cDNA_R1.fastq and cDNA_R2.fastq files.

Is that normal to have CITE-seq-Count running fine but without HTO (antibody barcode) in the HTO_R2.fastq file?

thanks,

Shan

**Comment by Hoohm** [comment]
Hello @shannjiang,

you might have some reads here and there that are in both libraries if the protocol is not super clean but I would only worry about it if you have similar numbers in each libraries that are linked to real barcodes.

Normally your cDNA and HTO libraries are split by index which is then demultiplexed after sequencing to split them.

**Comment by shannjiang** [comment]
@Hoohm So do you think it's totally fine in my case? As long we have similar numbers in each libraries that are linked to real barcodes?

If it is so, I am wondering how this command is working totally fine even without HTOs in the TAGS_R2.fastq.gz:
CITE-seq-Count -R1 TAGS_R1.fastq.gz -R2 TAGS_R2.fastq.gz -t TAG_LIST.csv -cbf X1 -cbl X2 -umif Y1 -umil Y2 -cells EXPECTED_CELLS -o OUTFOLDER

**Comment by Hoohm** [comment]
Do you get high numbers of HTO? I'm guessing mostly you should get unmapped high results.
What does the report look like?

**Comment by Hoohm** [comment]
Any updates regarding this issue?

**Comment by shannjiang** [comment]
Hi Patrick Roelli,

Thanks for the comment. I am asking someone in my lab to check if most of these reads were unmapped because I am not the person to run the pipeline directly.
I found an error info in the log file:
[WARNING] Read1 length is 28bp but you are using 26bp for Cell and UMI barcodes combined.This might lead to wrong cell attribution and skewed umi counts.
From my understanding, if that means the sequences for the genome are only 2/28 because these barcodes took a large proportion of the read1 (26/28)?

So probably our experiments were failed?

thanks,
Shann


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Hoohm** [comment]
Oh no, not at all.

It just means that R1 is 28bp of length but you are using only 26bp from R1.
I've added this warning because sometimes people make a mistake int he cell barcode or umi attribution.

This probably just means that you sequenced 28 instead of 26 for R1. Nothing to worry about.

**Comment by shannjiang** [comment]
Thanks @Hoohm , yes you are right, most of these reads were unmapped. I would close the thread.
