### ISSUE TITLE
CITEseq count results 100% unmapped

### ISSUE THREAD

**Issue by hsd676** [Hoohm/CITE-seq-Count#131]
Hi, we performed cell hashing with 4 HTO antibodies, 10XV3.3 Chemistry. 
We used CITE-seq count v 1.4.3, with following parameters 
CITE-seq-Count -R1 R1.fastq.gz -R2  R2.fastq.gz -/hto.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 5000 --sliding-window --max-errors 3 -o /NABX -- debug. I got 100% unmapped. 
I changed the max-errors to upto 6 and started getting ~ 20% mapped results. 

As you had suggested other users, I used grep to search for my HTO tags in R2 reads, but could never find matches for the entire length of the TAG, for instance with TAG -ACCCACCAGTAAGAC, I got matches for 6-8 bps, for example CACCAGTA or ACCCACC. Is this correct? 

I therefore started tweaking the parameters and used -- sliding window with max errors -6 and got 90% mapped. Will this be an issue during further processing?

**Comment by hsd676** [comment]
I also noticed one more thing: The UMI count for the HTO tags was > 5000. Is this normal?
            ACGATGTTCCGCATAA    CCACGTTGTAGCCAA 
HTO1       6512                                5009
HTO2      5865                                4849
HTO3      5230                                4111
HTO4     10955                               9113

**Comment by Hoohm** [comment]
Hello @hsd676,

A high mismatch rate like this is usually not a good idea. I would recommend you try and figure out why you're matching only partial sequences.

What comes after and before your insert that seems proper?
Is it starting in the same position usually?

You kind of have to "explore" a bit your data using greps and figuring out what happened.

You should not have to use sliding windows on classic HTO data. I would deactivate this option.

**Comment by hsd676** [comment]
Thanks for the quick response. It turns out that the core did not sequence the HTO library. We were trying to map the R1/R2 Transcriptome reads. No wonder we got 0% mapped. 
Hitesh

**Comment by Hoohm** [comment]
Ok closing this then :)
