### ISSUE TITLE
Unable to load run_report.yaml

### ISSUE THREAD

**Issue by hisplan** [Hoohm/CITE-seq-Count#133]
```
import yaml

with open(os.path.join(path_data, "report/run_report.yaml"), "rt") as fin:
  report = yaml.load(fin, Loader=yaml.FullLoader)        
```

I'm getting this error:

```
while scanning for the next token
found character '\t' that cannot start any token
```

I believe YAML shouldn't include tabs as indentation. I'm using YAML 5.3.1.

**Comment by Hoohm** [comment]
Hey @hisplan and thank you for your issue.

You are totally right. I will include this in the future release.

Thank you.

**Comment by wflynny** [comment]
Any updates on this issue?  Snooped around the dev branch and it looks like it's still custom formatting rather than using `pyyaml` or another package.  

Currently getting around it by doing:
```{python}
import yaml

with open("path/to/run_report.yaml", "r") as fin:
    content = fin.read().replace("\t", "  ")
    report = yaml.load(content, Loader=yaml.FullLoader)
```

**Comment by Hoohm** [comment]
Should be fixed in the latest version
