### ISSUE TITLE
Unequal number of read1 ({}) and read2({}) files provided

### ISSUE THREAD

**Issue by kdragicevic** [Hoohm/CITE-seq-Count#134]
Hi, 

just wanted to point out a small issue that you could maybe solve, cause maybe other users have the same problem but don't know  how to deal with it. 

In the source code file: CITE-seq-Count/cite_seq_count/preprocessing.py
somewhere around line number 307, you have this error message that pops up if the files have not the same number of reads or whatever. Anyway, I had that message popping up yesterday for the whole day and I was kinda confused because the files were properly written, nothing was corrupted and I have also put the absolute file path to them. Then I looked into your source code and it turns out that I cannot put the absolute path to the read1 and read2 files because it somehow reads it wrong. I have no idea why (I am not that much into python and linux and I know only the basic commands), but I knew that it has something to do with the file paths. Anyway, I changed my working directory to the folder where the fastq.gz files are and then ran the whole thing with only the file names and it worked. 

So from: 

- CITE-seq-Count **-R1 /SOMEPATH/sample1_L001_R1_001.fastq.gz -R2 /SOMEPATH/sample1_L001_R2_001.fastq.gz** -t /SOMEPATH/tags.csv

to 

- CITE-seq-Count **-R1 sample1_L001_R1_001.fastq.gz -R2 sample1_L001_R2_001.fastq.gz** -t tags.csv

I think it shouldn't be necessary to be in the directory where the files are, because the point is that you can always put a path as a command and it should be recognizing it if it's a properly written path. At least that's my opinion :-). Or maybe you could say in the documentation that the user should change the working directory to the one where the fastq.gz files are. :-) That would also solve the issue. 

Anyway, great program all in all! :-D

**Comment by Hoohm** [comment]
Hey @kdragicevic 
this is now fixed in 1.4.4.

I'll let you test it out.
