### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by aedin** [Hoohm/CITE-seq-Count#136]
Ran for 10 hours and no output. No temp files.  Tried on 2 servers running different versions of Python 3.5.2 :: Continuum Analytics, Inc. and Python 3.6.6 :: Anaconda, Inc. First server has 56 threads,640GB memory second one has 32 threads	 	384GB memory. Both have 	Ubuntu 16.04

CITE-seq-Count  -R1 ./HM37LDRXX_All_unmapped.1.fastq.gz  -R2 ./HM37LDRXX_All_unmapped.2.fastq.gz -t cite_seq_tags.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 25000 -o outs 

So I tested on a smaller set 

CITE-seq-Count  -R1 ./HM37LDRXX_All_unmapped.1.fastq.gz  -R2 ./HM37LDRXX_All_unmapped.2.fastq.gz -t cite_seq_tags.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 25000 -o outs -n 100000

it writes a file outs, that is a csv file  not a folder.

So reading recent issue, I added threads using the -T or --threads parameter (on https://hoohm.github.io/CITE-seq-Count/Running-the-script/#optional)  but I get an error that it doesn't recognize -T or --threads

CITE Seq Count: error: unrecognized arguments: --threads 5
CITE Seq Count: error: unrecognized arguments: -T 5

**Comment by Hoohm** [comment]
That's odd, what version are you running?

**Comment by aedin** [comment]
I checked I have two versions installed and it was defaulting to the older one.  I deleted and reinstalled. However -T still not working



Defaulting to user installation because normal site-packages is not writeable
Processing 
~/.cache/pip/wheels/f4/08/a6/b881b50182549229dc4ae9d75ee0d7cd8776d510f93879679d/CITE_seq_Count-1.4.3-py3-none-any.whl
Requirement already satisfied: multiprocess>=0.70.6.1 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (0.70.10)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/anaconda3/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (0.23.4)
Requirement already satisfied: python-levenshtein>=0.12.0 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (0.12.0)
Requirement already satisfied: scipy>=1.1.0 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (1.5.2)
Requirement already satisfied: pytest==4.1.0 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (4.1.0)
Requirement already satisfied: umi-tools==1.0.0 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (1.0.0)
Requirement already satisfied: pybktree==1.1 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (1.1)
Requirement already satisfied: pytest-dependency==0.4.0 in ~/.local/lib/python3.6/site-packages (from CITE-seq-Count==1.4.3) (0.4.0)
Requirement already satisfied: dill>=0.3.2 in ~.local/lib/python3.6/site-packages (from multiprocess>=0.70.6.1->CITE-seq-Count==1.4.3) (0.3.2)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/anaconda3/lib/python3.6/site-packages (from pandas>=0.23.4->CITE-seq-Count==1.4.3) (2.8.1)
Requirement already satisfied: pytz>=2011k in /usr/local/anaconda3/lib/python3.6/site-packages (from pandas>=0.23.4->CITE-seq-Count==1.4.3) (2019.3)
Requirement already satisfied: numpy>=1.9.0 in ~/.local/lib/python3.6/site-packages (from pandas>=0.23.4->CITE-seq-Count==1.4.3) (1.19.2)
Requirement already satisfied: setuptools in /usr/local/anaconda3/lib/python3.6/site-packages (from python-levenshtein>=0.12.0->CITE-seq-Count==1.4.3) (45.2.0.post20200210)
Requirement already satisfied: atomicwrites>=1.0 in ~/.local/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (1.4.0)
Requirement already satisfied: more-itertools>=4.0.0 in ~/.local/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (8.5.0)
Requirement already satisfied: pluggy>=0.7 in ~/.local/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (0.13.1)
Requirement already satisfied: six>=1.10.0 in /usr/local/anaconda3/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (1.14.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/anaconda3/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (17.4.0)
Requirement already satisfied: py>=1.5.0 in /usr/local/anaconda3/lib/python3.6/site-packages (from pytest==4.1.0->CITE-seq-Count==1.4.3) (1.5.2)
Requirement already satisfied: matplotlib in ~/.local/lib/python3.6/site-packages (from umi-tools==1.0.0->CITE-seq-Count==1.4.3) (3.3.2)
Requirement already satisfied: future in ~/.local/lib/python3.6/site-packages (from umi-tools==1.0.0->CITE-seq-Count==1.4.3) (0.18.2)
Requirement already satisfied: regex in ~/.local/lib/python3.6/site-packages (from umi-tools==1.0.0->CITE-seq-Count==1.4.3) (2020.9.27)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in ~/.local/lib/python3.6/site-packages (from pluggy>=0.7->pytest==4.1.0->CITE-seq-Count==1.4.3) (2.0.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/anaconda3/lib/python3.6/site-packages (from matplotlib->umi-tools==1.0.0->CITE-seq-Count==1.4.3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ~/.local/lib/python3.6/site-packages (from matplotlib->umi-tools==1.0.0->CITE-seq-Count==1.4.3) (1.2.0)
Requirement already satisfied: certifi>=2020.06.20 in ~/.local/lib/python3.6/site-packages (from matplotlib->umi-tools==1.0.0->CITE-seq-Count==1.4.3) (2020.6.20)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /usr/local/anaconda3/lib/python3.6/site-packages (from matplotlib->umi-tools==1.0.0->CITE-seq-Count==1.4.3) (2.2.0)
Requirement already satisfied: pillow>=6.2.0 in ~/.local/lib/python3.6/site-packages (from matplotlib->umi-tools==1.0.0->CITE-seq-Count==1.4.3) (7.2.0)
Requirement already satisfied: zipp>=0.5 in ~/.local/lib/python3.6/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pluggy>=0.7->pytest==4.1.0->CITE-seq-Count==1.4.3) (3.2.0)
Installing collected packages: CITE-seq-Count
Successfully installed CITE-seq-Count-1.4.3

**Comment by aedin** [comment]
If I look at the input parameters it doesn't mention threads

 CITE-seq-Count
usage: CITE-seq-Count [-h] -R1 READ1_PATH -R2 READ2_PATH -t TAGS -cbf CB_FIRST
                      -cbl CB_LAST -umif UMI_FIRST -umil UMI_LAST
                      [--umi_collapsing_dist UMI_THRESHOLD]
                      [--no_umi_correction]
                      [--bc_collapsing_dist BC_THRESHOLD] -cells
                      EXPECTED_CELLS [-wl WHITELIST] [--max-errors MAX_ERROR]
                      [-trim START_TRIM] [--sliding-window] [-T N_THREADS]
                      [-n FIRST_N] [-o OUTFOLDER] [--dense] [-u UNMAPPED_FILE]
                      [-ut UNKNOWNS_TOP] [--debug] [--version]

This script counts matching antibody tags from paired fastq files. Version 1.4.3

optional arguments:
  -h, --help            show this help message and exit
  -T N_THREADS, --threads N_THREADS
                        How many threads are to be used for running the program
  -n FIRST_N, --first_n FIRST_N
                        Select N reads to run on instead of all.
  -o OUTFOLDER, --output OUTFOLDER
                        Results will be written to this folder
  --dense               Add a dense output to the results folder
  -u UNMAPPED_FILE, --unmapped-tags UNMAPPED_FILE
                        Write table of unknown TAGs to file.
  -ut UNKNOWNS_TOP, --unknown-top-tags UNKNOWNS_TOP
                        Top n unmapped TAGs.
  --debug               Print extra information for debugging.
  --version             Print version number.

Inputs:
  Required input files.

  -R1 READ1_PATH, --read1 READ1_PATH
                        The path of Read1 in gz format, or a comma-separated list of paths to all Read1 files in gz format (E.g. A1.fq.gz,B1.fq,gz,...
  -R2 READ2_PATH, --read2 READ2_PATH
                        The path of Read2 in gz format, or a comma-separated list of paths to all Read2 files in gz format (E.g. A2.fq.gz,B2.fq,gz,...
  -t TAGS, --tags TAGS  The path to the csv file containing the antibody
                        barcodes as well as their respective names.
                        
                        Example of an antibody barcode file structure:
                        
                        	ATGCGA,First_tag_name
                        	GTCATG,Second_tag_name

Barcodes:
  Positions of the cellular barcodes and UMI. If your cellular barcodes and UMI
   are positioned as follows:
  	Barcodes from 1 to 16 and UMI from 17 to 26
  then this is the input you need:
  	-cbf 1 -cbl 16 -umif 17 -umil 26

  -cbf CB_FIRST, --cell_barcode_first_base CB_FIRST
                        Postion of the first base of your cell barcodes.
  -cbl CB_LAST, --cell_barcode_last_base CB_LAST
                        Postion of the last base of your cell barcodes.
  -umif UMI_FIRST, --umi_first_base UMI_FIRST
                        Postion of the first base of your UMI.
  -umil UMI_LAST, --umi_last_base UMI_LAST
                        Postion of the last base of your UMI.
  --umi_collapsing_dist UMI_THRESHOLD
                        threshold for umi collapsing.
  --no_umi_correction   Deactivate UMI collapsing
  --bc_collapsing_dist BC_THRESHOLD
                        threshold for cellular barcode collapsing.

Cells:
  Expected number of cells and potential whitelist

  -cells EXPECTED_CELLS, --expected_cells EXPECTED_CELLS
                        Number of expected cells from your run.
  -wl WHITELIST, --whitelist WHITELIST
                        A csv file containning a whitelist of barcodes produced by the mRNA data.
                        
                        	Example:
                        	ATGCTAGTGCTA
                        	GCTAGTCAGGAT
                        	CGACTGCTAACG
                        
                        Or 10X-style:
                        	ATGCTAGTGCTA-1
                        	GCTAGTCAGGAT-1
                        	CGACTGCTAACG-1

TAG filters:
  Filtering and trimming for read2.

  --max-errors MAX_ERROR
                        Maximum Levenshtein distance allowed for antibody barcodes.
  -trim START_TRIM, --start-trim START_TRIM
                        Number of bases to discard from read2.
  --sliding-window      Allow for a sliding window when aligning.

**Comment by aedin** [comment]
Also I  would be grateful if you could give me some guidance on the number of cells. It seems if the number of cells (-cells) is less than the actual number of cells, it looks for a whitelist

-n 25000
Started mapping
Processing 80,000 reads
CITE-seq-Count is running with one core.
Mapping done for process 42986. Processed 80,000 reads
Mapping done
Number of expected cells, 25000, is higher than number of cells found 21982.
Not performingcell barcode correction
Correcting umis

-n 250
Started mapping
Processing 80,000 reads
CITE-seq-Count is running with one core.
Mapping done for process 43260. Processed 80,000 reads
Mapping done
Correcting cell barcodes
Looking for a whitelist
Collapsing cell barcodes
Correcting umis

**Comment by aedin** [comment]
It is ignoring threads

CITE-seq-Count  -R1 ./HM37LDRXX_All_unmapped.1.fastq.gz  -R2 ./HM37LDRXX_All_unmapped.2.fastq.gz -t ./cite_seq_tags.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 800000  --threads 10 -o Outtests -n 100000
Started mapping
Processing 100,000 reads
CITE-seq-Count is running with one core.
Mapping done for process 2025966. Processed 100,000 reads
Mapping done
Number of expected cells, 800000, is higher than number of cells found 25223.
Not performingcell barcode correction
Correcting umis

**Comment by Hoohm** [comment]
You need python 3.6 to be able to use the latest version

**Comment by aedin** [comment]
Thanks, its working now. It seems to auto use threads, but ignores -T option

**Comment by Hoohm** [comment]
Ok great!
