### ISSUE TITLE
https://www.ebi.ac.uk/ena/data/view/PRJNA393315 10x or drop-seq data

### ISSUE THREAD

**Issue by 2236529177** [Hoohm/CITE-seq-Count#14]
dear professor,
Thanks for your great CITE-seq. I am reading your paper of "simultaneous epitope and transcriptome measurement in single cells", I want to know the data you posted in EBI is just 10x or Drop-seq in website https://www.ebi.ac.uk/ena/data/view/PRJNA393315 , because net speed here is very low, thanks a lot

**Comment by Hoohm** [comment]
Dear @2236529177 
From a quick search in the paper, it seems that the method used in this specific paper is dropseq and not 10x.

I hope this helps
