### ISSUE TITLE
Confusion about input arguments

### ISSUE THREAD

**Issue by YingzhengXu** [Hoohm/CITE-seq-Count#149]
Hi Hoohm,

I am new to sc RNA seq and have a question about the inputs(R1, R2, Antibody tag) of CITE-seq-Count. If I was given GEX, HTO and ADT fastq files, could you point me to the specific files that CITE-seq requires for input? Also, the purpose of CITE-seq for me is to get the 10X-like matrix to complement Seurat.

**Comment by Hoohm** [comment]
Hello @YingzhengXu,

The simple answer is, you need the HTO raw fastq files and the HTO tag list. You also need to know where those barcodes are and how long they are.

The complex answer is, there are a lot of different chemistries and combinations of designs that might be involved in your experiment. You should ask Your colleagues about the design of the experiment and about the design of the chemistries and understand more specifically what is expected from you.

I'm sorry, but I'd rather not advise you on something that high level. I will gladly help you out with more specific questions later on in the process.

Best of luck to you.

**Comment by YingzhengXu** [comment]
Thank you @Hoohm! 

I had a closer look of fastQC report for HTO R2 and noticed a section called "Overrepresented sequences" where the sequences looked like antibody barcodes. Could you confirm if this is true? 
<img width="844" alt="Screen Shot 2021-02-06 at 11 25 23" src="https://user-images.githubusercontent.com/78630660/107128019-ffff7880-687f-11eb-8d08-104e6f8e3cc0.png">

When I removed the polyA tails, I saw some duplicates. Should I include only the unique Ab tags in the csv?

**Comment by Hoohm** [comment]
1. It seems like you have HTO tags in there, yes. You should have gotten a reference of those.
2. Cell number should be in line with what you found in the RNA data. I would suggest maybe 20% more to be sure to catch everything you need.

**Comment by YingzhengXu** [comment]
Thank you so much. It really helped me a lot!
