### ISSUE TITLE
Why this warning?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#15]
If you have a read length greater than the cell barcode + UMI length, the tool says:

"Read 1 length is 35bp but you are using 26bp for cell and UMI barcodes combined.
This might lead to wrong cell attribution and skewed umi counts"

Is this actually a problem though?  Doesnt it just ignore the final 9bp?  I could see this warning being useful to make sure the operator is confident with the barcode/UMI lengths chosen; however, there isnt actually a chance it would result in the incorrect cell barcode being chosen, is there?

**Comment by Hoohm** [comment]
Hello @bbimber 
You are right, the warning might be spelled out differently. I had some issues once with a user making a mistake in the cell and umi barcode attribution and wanted a warning to pop up to catch unexpected "errors".

However, in your case, it does not matter.

I'll change the warning to something a bit less dramatic in the next version.

Thanks for the feedback :)

**Comment by bbimber** [comment]
that's what I figured and what the code seemed to be doing.

I might suggest something more like "Read 1 length is 35bp but you are using 26bp for cell and UMI barcodes combined.  Please be certain you are using the correct positions for the cell barcode and UMI"
