### ISSUE TITLE
Filtering UMIs on read number

### ISSUE THREAD

**Issue by rule-110** [Hoohm/CITE-seq-Count#151]
I have a very deeply sequenced barcodes library and I expect a substantial amount of UMIs to not be real. We expect those "fake" UMIs to have very low read numbers. Is there a possibility to select only the UMIs that passes a certain read threshold. Also is it possible to have the distribution, like an histogram, of the number of reads per UMIs?

Thanks a lot

**Comment by Hoohm** [comment]
Hello @rule-110 ,

there is no thresholding at the moment. Mainly because I would rather have raw results come out for users to make their own choice post processing.

I would suggest a downsampling approach to get rid of the lowlevel UMIs for the moment.
