### ISSUE TITLE
How can I handle with a separated cell barcode sequence?

### ISSUE THREAD

**Issue by TaskeHAMANO** [Hoohm/CITE-seq-Count#153]
Thanks for providing a useful stuffs.

I have a TotalSeq tag reads and WTA reads, which are sequenced by BD Rhapsody.
As you check the sequence structure [here](https://teichlab.github.io/scg_lib_structs/methods_html/BD_Rhapsody.html), the cell barcode sequence of BD Rhapsody is separated to three parts.
Then, how can I set `-cbf` and `-cbl` option?

**Comment by Hoohm** [comment]
Hello @TaskeHAMANO 

there is no direct way of handling this kind of data today through CSC.

There is a way though. You can trim out any sequence that is not a barcode and regenerate R1 without those.
Then you can run CSC as usual.

Hope this helps

**Comment by TaskeHAMANO** [comment]
@Hoohm 

Thank you for providing your idea. It seems not so difficult. I will try!
