### ISSUE TITLE
Running CITE-seq-Count on ASAP-seq

### ISSUE THREAD

**Issue by jhjlee** [Hoohm/CITE-seq-Count#154]
Hi,

Thanks for making this useful tool!

I have a question about running CITE-seq-Count on ASAP-seq. We did ASAP-seq to hashtag cells.

There are three FASTQ files and according to this document (https://citeseq.files.wordpress.com/2020/09/asap_seq_bridge_a_hashing.pdf) and they are structured in this way:
        R1 containing Genomic fragment including UBI (analogous to UMI) at positions 1-10.
        R2 containing cell barcode at positions 1-16.
        R3 containing Genomic fragment including hashtag at positions 1-15.

Since CITE-seq-Count accepts only two sets of FASTQ files (R1 and R2), I appended R2 and R1 together and provided the appended FASTQ file as an input for [-R1] parameter, and R3 FASTQ file for [-R2] parameter. And given the lengths of cell barcode and UBI, this parameter was provided [-cbf 1 -cbl 16 -umif 17 -umil 26]. 

I'm wondering whether the above approach is sensible for ASAP-seq? Reason I'm asking is I obtained an output that doesn't match up with the accompanying scATAC-seq data - no common cell barcodes across them. 

Thanks!

**Comment by Hoohm** [comment]
Hello @jhjlee 
your strategy is totally fine here. What might have happened is that the V3 chemistry of 10x has two different barcodes per cell, one for the RNA one for the FB.

When you give a specific list of RNA, it will probably not overlap at all with the FB barcodes.

From here you have two options.

1. run the current release without providing a specific list of cells to find but rather a number.
Once you get this back, "translate" the barcodes based on the translation list found [here](https://github.com/10XGenomics/cellranger/blob/master/lib/python/cellranger/barcodes/translation/3M-february-2018.txt.gz)
2. Run the experimental branch https://github.com/Hoohm/CITE-seq-Count/tree/feature/cells_argument and this should provide an MTX output with both RNA and FB barcodes in the barcodes.tsv output. Please try on a lower portion of the data if you choose this option. There is an argument that allows you to get only the top N reads, just to see that it runs through. This version will ask you for a Reference "Translation" list, the link I posted in the previous paragraph.

Option 1 is safer, but a bit more manual work, option 2 might crash, I've been working on it off and on lately. So there are definitely bugs in there I have not accounted for.

Please let me know if you need any help to go through this.

**Comment by jhjlee** [comment]
Hi thanks for you reply!

I'm a little confused though because what I'm trying to do is to demultiplex ASAP-seq data (accompanying scATAC-seq). When I did option 1 and tried translating the barcodes with the translation list, I had no hits. Isn't this translation list for scRNA-seq instead? Sorry if I'm misunderstanding you.

**Comment by Hoohm** [comment]
Totally possible, I imagined it would be the same chemistry.

Did you try and grep some barcodes in the library to find out if they are
in there at all?

**Comment by jhjlee** [comment]
Yes I did and couldn't get any matches. I think the barcodes for scATAC-seq (and by extension ASAP-seq) and barcodes scRNA-seq are different.

**Comment by Hoohm** [comment]
Yeah I'm not familiar with the technology.

Any chance there is a translation table?

If not, could you maybe send top 10 barcodes from a couple of millions of
reads?

**Comment by jhjlee** [comment]
Hi I think I figured out the problem here. Apparently the cell barcodes in the ASAP-seq data needs to be reverse complemented (source: https://github.com/caleblareau/asap_to_kite). When I did this and ran CITE-seq-Count again, I could pick up signals from the data. 
Thanks for looking into this and happy to close the issue.

**Comment by Hoohm** [comment]
Nice!
Happy to help :)
And I got to learn something as well, thanks
