### ISSUE TITLE
Error when option are set to --bc_collapsing_dist 0 

### ISSUE THREAD

**Issue by rule-110** [Hoohm/CITE-seq-Count#157]
Hello,

I am using Cite-seq-count 1.4.4 and when I set the option --bc_collapsing_dist  to 0 (but not when I set it to 1) I got this error
```

\ File "...conda/envs/py3/bin/CITE-seq-Count", line 11, in <module>
    load_entry_point('CITE-seq-Count==1.4.4', 'console_scripts', 'CITE-seq-Count')()
  File "...conda/envs/py3/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 394, in main
    ab_map=ordered_tags_map)
  File "...conda/envs/py3/lib/python3.6/site-packages/cite_seq_count/processing.py", line 368, in correct_cells
    ab_map=ab_map,
  File "...conda/envs/py3/lib/python3.6/site-packages/cite_seq_count/processing.py", line 312, in collapse_cells
    for real_barcode in true_to_false:
TypeError: 'NoneType' object is not iterable
```

I saw that this error was raised by other users, but I thought it was fixed in version 1.4.4. Do I am doing anything wrong or is there anything I could do to fix this?

Thanks
Nicolas

**Comment by Hoohm** [comment]
Hello @rule-110 
I just pushed a hotfix, should deal with the issue and skip barcode correction when using a value that is less than 0.

Please let me know if it works for you.

**Comment by rule-110** [comment]
Yes it works great with the hotfix. Thanks
