### ISSUE TITLE
Issue with No module named 'Levenshtein'

### ISSUE THREAD

**Issue by Lopiniatre** [Hoohm/CITE-seq-Count#164]
Thank you for developing this nice tool.
I have a small issue when trying to run CITE-seq-Count in conda, it returns
`No module named 'Levenshtein'`
I run on a cluster with python 3.7, and installed CITE-seq-Count through bioconda (since I cannot use pip).
I  can't seem to find a Levenshtein module to install in Conda that is compatible with python 3.7.
Do you know if it's currently possible to run the CITE-seq-Count through Conda installations? Do you have a recommended version for all dependencies and this Levenshtein module, or a possible workaround? This was not caught during install apparently.

Thanks!

**Comment by Hoohm** [comment]
Hello @Lopiniatre
that's a good question. Didn't even know CSC was on conda.

To be honest I don't how why it's not installed. It is in the list of packages to be installed in the setup.py

have you tried installing CSC through pip on your conda install instead?

**Comment by Lopiniatre** [comment]
Hi @Hoohm 
Thank you for your answer! I installed using pip in the conda environment and it did install Levenshtein correctly. Hopefully that will stay ok in the environment. Maybe someone will solve the conda version issue.
Best!
