### ISSUE TITLE
bug in  preprocessing.py  ->  get_read_paths()  (version 1.4.3)

### ISSUE THREAD

**Issue by AlexSurnov** [Hoohm/CITE-seq-Count#175]
Dear developers of CITE-Seq-Count,
Thank you for your product.

I installed CITE-Seq-Count version 1.4.3 and I think that there is an inconsistency in the file `preprocessing.py`. Namely, the function `get_read_paths` contains the line `if len(read1_path) != len(read2_path):` instead of `if len(_read1_path) != len(_read2_path):`. To my understanding, this is a crucial bug, which prevents proper input reading. When the incorrect line is executed, the script compares the number of characters in the input strings instead of the number of elements in the split strings generated by the `read1_path.split`.

All the best
Alex Surnov

**Comment by Hoohm** [comment]
This is correct, this bug is fixed in 1.4.5
