### ISSUE TITLE
method keeps looking for whitelist when not provided.

### ISSUE THREAD

**Issue by naila53** [Hoohm/CITE-seq-Count#176]
Hi, 
I'm trying to run Cite-seq-count without a whitelist argument, however, it keeps being stuck at the looking for whitelist step after finishing the mapping for hours!
![image](https://user-images.githubusercontent.com/56326205/221026317-738a5e7a-c901-476d-89ee-535eaa962ef1.png)

**Comment by Hoohm** [comment]
Hello,

How many cells are you looking for? Might be that the parameter is set too
high

**Comment by naila53** [comment]
Hi,
I set the cells parameters to 1million, just thinking of retrieving empty droplets. That's too high right?

**Comment by Hoohm** [comment]
You should set it to the expected cells.

I think I add 20% to be sure to capture all possible cells.

**Comment by naila53** [comment]
hi, I need to retrieve the empty droplets for the sake of normalization, to model noise component. I have run your method about a year ago and you can see I posted a different issue here about totalseqB https://github.com/Hoohm/CITE-seq-Count/issues/158 
but the point is I used high number of cells as you can see in my run info to retrieve the empty droplets. 
I tried again with inputting the raw unfiltered cellranger barcodes list as a whitelist for my data 
and kept the -cells argument at 1million cells , it still keeps getting stuck at the final step for hours! and it looks like it's trying to process more than 1million!
 I think something has changed in the new version, because it ran fine on all my previous totalseqA data..
![image](https://user-images.githubusercontent.com/56326205/221341004-475a0061-210e-41c5-af06-2c88a47cb257.png)

**Comment by Hoohm** [comment]
Interesting.

I can't get into it atm as I'm on holiday.
I suggest you try the older version then.

https://stackoverflow.com/questions/5226311/installing-specific-package-version-with-pip#5226504

The old version will give you the same counts as the new one.

**Comment by naila53** [comment]
thank you so much for your prompt response! I tried reinstalling the older version and I seem to have resolved this. However, I tried to reproduce my previous analysis, I seem to have a new issue with both new and old version where it fails at the very last step! 
![image](https://user-images.githubusercontent.com/56326205/221371131-8e1dd403-2a08-407c-bd84-e0b6efdefd52.png)

**Comment by Hoohm** [comment]
This is related to the python version.
I think it has to be under 3.6 to fix that

**Comment by naila53** [comment]
yes, it is! installed python 3.7 and worked! thank you so much!
