### ISSUE TITLE
Gene and Antibody both have a pair of fastq files, how to run CITE-seq-Count?

### ISSUE THREAD

**Issue by edceeyuchen** [Hoohm/CITE-seq-Count#189]
My files are below:
Ab_C0042-25CN_S0_L001_I1_001.fastq.gz
Ab_C0042-25CN_S0_L001_R1_001.fastq.gz
Ab_C0042-25CN_S0_L001_R2_001.fastq.gz
GEX_C0042-25CN_S0_L001_I1_001.fastq.gz
GEX-C0042-25CN_S0_L001_R1_001.fastq.gz
GEX-C0042-25CN_S0_L001_R2_001.fastq.gz

**Comment by edceeyuchen** [comment]
My files are below:
Ab_C0042-25CN_S0_L001_I1_001.fastq.gz
Ab_C0042-25CN_S0_L001_R1_001.fastq.gz
Ab_C0042-25CN_S0_L001_R2_001.fastq.gz
GEX_C0042-25CN_S0_L001_I1_001.fastq.gz
GEX-C0042-25CN_S0_L001_R1_001.fastq.gz
GEX-C0042-25CN_S0_L001_R2_001.fastq.gz

**Comment by luostrowski** [comment]
Were you able to figure this out?

**Comment by Hoohm** [comment]
Hello,
CITE-seq-Count only runs on antibody fastq files, you need to merge them back using the cell barcode later after preprocessing.

Hope this helps.
