### ISSUE TITLE
Variable TAG lengths?

### ISSUE THREAD

**Issue by santiagorevale** [Hoohm/CITE-seq-Count#19]
Hi there,

I was wondering, do you actually believe/expect to have projects mixing TAGs of variable length? Do you really think this is a possibility?

I've been checking the lengths within different suppliers, and the lengths are always consistent.

Thanks in advance.

Cheers,
Santiago

**Comment by Hoohm** [comment]
Hey @santiagorevale 
It did happen sometimes when testing new protocols if I recall. Mixing HTOs and TAGs for example.
