### ISSUE TITLE
Read length not consistent

### ISSUE THREAD

**Issue by dpcook** [Hoohm/CITE-seq-Count#23]
Hey there,

I got the error: 
`Read2 length is not consistent, please trim all Read2 reads at the same length`

So I checked the length of the R2 reads and some were a bit shorter, so I trimmed everything down to 15bp (barcode is in the first 8bp anyway). Now the reads are all the same length
![image](https://user-images.githubusercontent.com/18197806/48380138-a01bc680-e6a4-11e8-9242-b1e5e3c9b13f.png)

And it's still returning the same error. Any ideas??

Here's the call:
`CITE-seq-Count \
-R1 /global/scratch/hpc3837/barcode_emt/fastq/Mix-1-Barcode/Mix-1-Barcode_R1_Merged.fastq.gz \
-R2 /global/scratch/hpc3837/barcode_emt/fastq/Mix-1-Barcode/Mix-1-Barcode_R2_Merged_Trimmed.fastq.gz \
-t /global/scratch/hpc3837/barcode_emt/data/LMOlist.csv \
-cbf 1 -cbl 16 -umif 17 -umil 26 -hd 1 -cells 30000 \
-o CiteSeqCount_Mix1_NoWL.tsv`

**Comment by dpcook** [comment]
And if it helps, here's a couple lines of the fastq file (gunzipped)

A6AAAEEEEEEEEEE
@NS500366:96:HMKWTBGX7:4:23612:9362:20396 2:N:0:TTAGGCAT
ATCTCGGAAAAAAAA
+
AAAAAEEEEEEEEEE
@NS500366:96:HMKWTBGX7:4:23612:14809:20396 2:N:0:TTAGGCAT
AACACCGTAAAAAAA
+
AAAAAEEEEEEEEEE
@NS500366:96:HMKWTBGX7:4:23612:19379:20396 2:N:0:TTAGGCAT
ATCTCGGAAAAAAAA
+
AAAAAE/EEEEEEEE
@NS500366:96:HMKWTBGX7:4:23612:14661:20396 2:N:0:TTAGGCAT
TGCGCGTGAAAAAAA

**Comment by Hoohm** [comment]
Hello @dpcook 
This is very strange indeed.

Just to be sure. Can you give me the first 4 lines of the file?

**Comment by dpcook** [comment]
Hey @Hoohm--thanks for the reply! Here's one of the entries in R2:

@NS500366:96:HMKWTBGX7:1:23312:17443:20387 2:N:0:NTAGGCAT
ATAGCGTCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCC
+
AAAAAEEEEEEEEAE6EEEEEE6EEEEEE<EEAA/A////////////66666666

It seems that the error might have been due to variable read length in R1 (a small handful were a base or two too short). To see if it was the problem, I used Trimmomatic to crop R2 down to 26bp **and** remove pairs where R1 was <26bp, it seemed to get around the error message.

**Comment by Hoohm** [comment]
Hey @dpcook 
I see there is an error in the code. It will always return an error about R2 even if it finds it in R1.
I'll fix that soon so that people are no longer confused.

Sorry about that

**Comment by dpcook** [comment]
Thanks for taking the time to look into it! :)

**Comment by Hoohm** [comment]
v1.3.3 has the new text. It's not released on pypi yet but you can get it from github
