### ISSUE TITLE
Running without UMI

### ISSUE THREAD

**Issue by benslack19** [Hoohm/CITE-seq-Count#26]
Hi, thanks for producing the CITE-seq-Count package. Sorry if this is more of a question than an issue. I'm just curious if it's possible to run CITE-seq-Count without UMI. We're interested in seeing how the data would look like with some experiments we're running. The UMI parameter of the call is "required", so I'm wondering if there's a way to get around this. Thanks.

**Comment by Hoohm** [comment]
Hey @benslack19 
I think you might be able to do that by giving the same number for the UMI position. If you have the cell barcode from 1 to 12, then try to use 12 and 12 for the umi. Try that, let me know how it goes

**Comment by Hoohm** [comment]
Hello @benslack19 
did this work at all?

**Comment by benslack19** [comment]
Hi @Hoohm,
Apologies for the delayed response. I did an initial trial but meant to try a few more things before reporting. In my initial trial, I put in positions for a pseudo-UMI and got counts that numbered in the 4000-5000 range, then I tried your recommendation and it went down to 200-300. I'll still try a few more things, but I'd think the number would go up right? Thanks.

**Comment by benslack19** [comment]
Thanks @Hoohm  for the suggestion. I'm a little bit of a noob, so could you provide a little more guidance? I want to make sure I'm doing this correctly. As I understand it, I see that repository has "feature/multi_processing" branch (with the underscore) but I'm a little unsure about how to properly use those scripts with my current installation. I'm currently running CITE-seq-Count through a virtual environment (~/anaconda3/envs/cite-seq/bin/CITE-seq-Count) if that facilitates your guidance.

**Comment by Hoohm** [comment]
No problem. The simplest way is to clone the repo somewhere then:

`cd into/repo`
`python setup.py install` or  `python setup.py install --user`

Then run using `/usr/bin/CITE-seq-Count` and not the one install on the conda env.

**Comment by benslack19** [comment]
Thanks for the tip @Hoohm. I assume I don't have to make changes to the call other than making sure I'm using the multi_processing version of the script? This is what I tried and I'm getting similar observations as I had before or maybe a little higher: using pseudo-UMI gives me counts in the 6000-8000 range while the UMI overlap brings it down to 300-500. Is it possible that I could be doing something wrong? I could video conference or discuss by phone if that's easier for you.

**Comment by Hoohm** [comment]
I'm closing this since we solved it through email.
The solution is to use the read counts instead of the umi counts.
