### ISSUE TITLE
ValueError: hamming expected two strings of the same length

### ISSUE THREAD

**Issue by chris-mcginnis-ucsf** [Hoohm/CITE-seq-Count#27]
Hello again --

I ran into the following error on a recent run:
ValueError: hamming expected two strings of the same length

Here is the command I used:
python /bin/CITE-seq-Count \
    -R1 /alpha/cmcginnis/BARS_3_S24_L007_R1_001.fastq.gz \
    -R2 /alpha/cmcginnis/BARS_3_S24_L007_R2_001.fastq.gz \
    -t /alpha/cmcginnis/CSCount/LMOlist.csv \
    -cbf 1 -cbl 16 -umif 17 -umil 26 -tr "[ATCG]{6}" -hd 1 \
    -wl /alpha/cmcginnis/HMEC1_WL.txt \
    -o CSCount_HMEC96orig_allIDs_120118.tsv

Any idea what would cause this error?

**Comment by Hoohm** [comment]
Hello @chris-mcginnis-ucsf 
I think this might be cause by an old version. I would recommend updating via pip and trying to run it again.

**Comment by Hoohm** [comment]
I'm closing this for now.
Feel free to reopen if it has not been solved.
