### ISSUE TITLE
Demultiplexing cite-seq sequencing data

### ISSUE THREAD

**Issue by kaizen89** [Hoohm/CITE-seq-Count#28]
Hi,
I'm about to have data from a 10X experiment with both HTO (4 tags)  and ADT antibodies (18 markers)
My question is; should I have one file for HTO and ADT or 1 for each type of antibodies.
I find only a description for demultiplexing the hashtags.
Thanks

**Comment by Hoohm** [comment]
Hello @kaizen89 
I'd recommend waiting a bit because the new version is almost coming out.
Here is the new documentation that might help you out: https://github.com/Hoohm/CITE-seq-Count/blob/feature/multi_processing/docs/docs/Running-the-script.md

Do you have different fastqs for adts and htos?

**Comment by kaizen89** [comment]
I have different oligos for ADT and HTO so I can get 2 if I ask the plateform to demultiplex using the 2 different oligos. But I dont know wether I shoud do it like this or just have  one file for both and one for mRNA. 
Should I have the ADT barcodes together with the HTO ones in the "tags.csv" file?

**Comment by Hoohm** [comment]
You can run everything together as long as the only difference is the tags (adt or hto).
The one thing you can't do is run tags with a constant region at the start of the read which is of a different length.

So if both ADTS and HTOs start at the same position in Read2, probably 0, then there is not problem to run everything together.

The other potential issue might be number of reads. I still have to test it to have a clear size estimation for 1million reads.
For a quick example I ran 50'000'000 reads on my laptop and it took around 3GB of memory.

**Comment by kaizen89** [comment]
These are the oligos:
for ADT
Illumina   Small RNA RPI1 primer ( i7 index 1, Oligonucleotide   sequences © 2015 Illumina, Inc)
5’CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA
for HTO
Illumina   TruSeq D701_s primer (for HTO amplification; i7 index 1)
5’CAAGCAGAAGACGGCATACGAGATCGAGTAATGTGACTGGAGTTCAGACGTGTGC.
They have different lenghts, so you suggest to treat them separately?

**Comment by Hoohm** [comment]
I was talking about the ADTs and HTOs themselves, not the oligos used by Illumina themselves.

**Comment by kaizen89** [comment]
So it turns out (as suggested by Biolegend people) that I should feed mRNA and ADT fastq files to cell ranger and HTO fastq files to cite-seq-count and should proceed with Seurat workflow.

**Comment by Hoohm** [comment]
I'm closing this for now.
Feel free to reopen if it has not been solved.
