### ISSUE TITLE
installation of 1.4

### ISSUE THREAD

**Issue by joonlee3** [Hoohm/CITE-seq-Count#30]
Hi,

   I was trying to install CITE-seq-Count v1.4. To perform clean-installation, I uninstalled CITE-seq-Count by using 'pip uninstall' command and reinstalled CITE-seq-Count by using 'pip install CITE-seq-Count'.

   After installation, it seems that v1.3.2 was installed instead of v1.4. Do you have any suggestions?

Thank you.
Joon

**Comment by Hoohm** [comment]
Hello @joonlee3 
yes, you can try to use this option: `--no-cache-dir`
it should clean the local version you have downloaded before.

**Comment by joonlee3** [comment]
Thank you for the quick reply. I followed your suggestion but v1.3.2 still seems to be installed.

**{0}: ./pip install CITE-seq-Count --no-cache-dir
Collecting CITE-seq-Count
  Downloading https://files.pythonhosted.org/packages/40/f6/a9837f7ce9ef253f496e807636530b961d78dee317685702f79bc2a1a5ca/CITE-seq-Count-1.3.2.tar.gz
Requirement already satisfied: regex>=2018.07.11 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from CITE-seq-Count) (2019.1.24)
Requirement already satisfied: python-levenshtein>=0.12.0 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from CITE-seq-Count) (0.12.0)
Requirement already satisfied: pandas>=0.23.3 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from CITE-seq-Count) (0.24.0)
Requirement already satisfied: setuptools in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from python-levenshtein>=0.12.0->CITE-seq-Count) (40.7.0)
Requirement already satisfied: numpy>=1.12.0 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from pandas>=0.23.3->CITE-seq-Count) (1.16.0)
Requirement already satisfied: pytz>=2011k in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from pandas>=0.23.3->CITE-seq-Count) (2018.5)
Requirement already satisfied: python-dateutil>=2.5.0 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from pandas>=0.23.3->CITE-seq-Count) (2.7.3)
Requirement already satisfied: six>=1.5 in /site/ne/home/wings/.pyenv/versions/3.5.2/lib/python3.5/site-packages (from python-dateutil>=2.5.0->pandas>=0.23.3->CITE-seq-Count) (1.11.0)
Installing collected packages: CITE-seq-Count
  Running setup.py install for CITE-seq-Count ... done
Successfully installed CITE-seq-Count-1.3.2**

**Comment by Hoohm** [comment]
What is your pip version?

**Comment by Hoohm** [comment]
Maybe it's because of python3.5. I would advise 3.6 at least also because of performance and memory issues. Could you try with 3.6?

**Comment by Hoohm** [comment]
I just double checked. Before 1.4.1 it was python3 required and now it's 3.6. That's probably why you get the old version

**Comment by joonlee3** [comment]
Sure, I will try.

Would you please describe the major bug in the previous version in more details? I am using 10x genomics technology. Do you expect some differences if I re-analyze our data by using v1.4?

Thank you so much.
Joon

**Comment by Hoohm** [comment]
Sure.One major difference is the umi correction. This wasn't done before 1.4.1 and it is now. This means that small sequencing mistakes might inflate some umi counts

**Comment by Hoohm** [comment]
Sure.

The bug in 1.3.4 was that the umi grouping was off and this gave an output that was in between reads and umis.

One major difference in the latest version is the umi correction. Small sequencing mistakes might have inflated some umi counts in the past. Depending on your sequencing quality, you might see a "clearer" picture to discriminate cells holding a tag or not.

**Comment by amayer21** [comment]
Hello, I would like to know if the bug was only in version 1.3.4 or also in previous versions. 
Thank you very much
Alice

**Comment by Hoohm** [comment]
Hello,
it was only in 1.3.4. The versions before had non corrected UMI counts.
Can I close this?

**Comment by amayer21** [comment]
OK, thank you very much.
