### ISSUE TITLE
output of version 1.4

### ISSUE THREAD

**Issue by rmenafra** [Hoohm/CITE-seq-Count#31]
Hi,
I just wanted to point out that (at least for me) the current output is compatible with cellranger3.0 format and can only be read if you install Seurat3 (latest version). Is that correct? 
However in Seurat3 the function HTOdemux is gone, so which kind of analysis flow would you recommend to do more or less the same than https://satijalab.org/seurat/hashing_vignette.html?

Thanks
Roberta

**Comment by Hoohm** [comment]
Hello Roberta.

Are you sure that HTOdemux is gone? Because I'm using Seurat V3 and I still got it.
Here is the exact name I have: `Seurat_3.0.0.9000`. If I'm not mistaken I installed it from git

**Comment by rmenafra** [comment]
I did install it a month ago from CRAN and I couldn't find that function, that's also why I went back to the previous version, maybe they implemented it later. I'll re-check, thanks for your quick reply.

**Comment by rmenafra** [comment]
Indeed I can see it now, but how do you reproduce HTOheatmap? (sorry if this is not strictly related to CITE-seq-Count).

**Comment by Hoohm** [comment]
I'm not sure what you are asking? Is the function not working as you expected?

**Comment by rmenafra** [comment]
I solved it, thanks. The HTOdemux is not working as expected but I posted an issue on the Seurat github page and it's not depending on the Seurat version I use.
