### ISSUE TITLE
correcting umis

### ISSUE THREAD

**Issue by DrKAD1** [Hoohm/CITE-seq-Count#32]
Hello,
Thanks for developing CITE-seq-Count.

I have been trying to run this for some time. However, i always get the error:root: no local minima was accepted...--plot-prefix etc error which I am ignoring since no cell barcode correction is done which is okay. But then i leave the pc for 1 or 2 days while the package is "correcting UMIs" only to find the process killed. I am running this on a linux OS with 64 Gb RAM.

To note, I am running this on my HTO library and using the filtered whitelist provided by cell ranger.
Please advise.
Thank you.

**Comment by Hoohm** [comment]
Hello @DrKAD1 
Other users had the same issue as you have.
Could you try the [develop](https://github.com/Hoohm/CITE-seq-Count/tree/develop) branch? I've changed which cells should get UMI corrected.
If this still fails, I added a new option: `--no_umi_correction`, which will skip the UMI correction.
I'm working on a better fix for next week.

**Comment by Hoohm** [comment]
Hello  @DrKAD1 
Haven't heard back from you. Did the develop branch help?

**Comment by Hoohm** [comment]
Fixed in 1.4.2. Closing this
