### ISSUE TITLE
Minimum hamming distance of TAGS barcode is less than given threshold

### ISSUE THREAD

**Issue by bishwaG** [Hoohm/CITE-seq-Count#33]
Hi,
Following are my antibody tags. I tried to run CITE-seq-Count  on 10X  data but got following error. Minimum hamming distance of the tags is 6. Since maximum allowed hammign distance is 3 by default, it is expected to have such error because if there is error in two sequences at most in 3 basepairs this gives rise to tag ambiguity. However, when I provide `--hamming-distance 2` I get the same error.

**Tags**:
```
CTCATTGTAACTCCT
TGTTCCCGCTCAACT
GCTGCGCTTTCCATT
AACCTAGTAGTTCGG
TTTGTCCTGTACGCC
ACCTTTATGCCACGG
ACTTCCGTCGATCTT
TCAATCCTTCCGCTT
GTCCCTGCAACTTGA
CCAGCTCATTAGAGC
GACCTCATTGTGAAT
AGTTCAGTCAACCGA
ACCTACCTGAGGTTA
TTTACTAAGTCGTTT
CTTCCGATTCATTCA
GGTTGCCAGATGTCA
TGTCTTTCCTGCCAG
CTCCTCTGCAATTAC
CAGTAGTCACGGTCA
```
**Command**:
``` sh
CITE-seq-Count --read1 $R1 --read2 $R2 \
        --tags TAG_LIST.csv \
        --cell_barcode_first_base 1 \
        --cell_barcode_last_base 16\
        --umi_first_base 17 \
        --umi_last_base 26 \
        --output $OUTPUT_DIR/$SAMPLE_R1".csv" \
        --whitelist $10X_WHITELIST_FILE \
       --hamming-distance 2
```
**ERROR**:
```
Minimum hamming distance of TAGS barcode is less than given threshold
Please use a smaller distance; exiting"
```

**Comment by Hoohm** [comment]
Hello @bishwaG 
this is strange because when I run the tags you gave here, I don't get the error mesage.

**Comment by Hoohm** [comment]
Is it possible that your tags are written like:
```
tag1,CGATCGA
tag2,CGTACGT
```
instead of 
```
CGTAGCTA,tag1
GCTGCTAC,tag2
```
?

**Comment by bishwaG** [comment]
Hi @Hoohm 
Thanks for your hint. Truly the issue was because of the order of the _tags_ and _tag-names_ columns.

**Comment by Hoohm** [comment]
Great! I'm closing this then.
