### ISSUE TITLE
output names are not compatible with Seurat Read10X

### ISSUE THREAD

**Issue by joonlee3** [Hoohm/CITE-seq-Count#34]
I've got three outputs after running CITE-seq-Count v1.4
- barcodes.tsv.gz
- features.tsv.gz
- matrix.mtx.gz

As suggested in the document page, I tried to use READ10X in Seurat (v3) but got an error since the READ10X specifically check the existence of three files
- barcodes.tsv
- genes.tsv
- matrix.mtx

Do you have any plan to make an adjustment to resolve this issue?  Thanks.

Best,
Joon

**Comment by Hoohm** [comment]
Hello @joonlee3 
could you paste the error here because I didn't have this issue with Seurat V3. Read10X is compatible with both older (<3.0) and newer (>3.0) versions of cellranger outputs.
Did you install Seurat through github?

**Comment by Mr-Laurent** [comment]
Hi @joonlee3 , I had the sameissue, but I found a solution on the 10XGenomic's website :
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices

in the "Loading matrices into R" section, they explain how to do it, and adapted to Cite-seq-Count, it should be something like this :  

`
library(Matrix)
matrix_dir = "/path_to_your_directory/out_cite_seq_count/umi_count/"
barcode.path <- paste0(matrix_dir, "barcodes.tsv.gz")
features.path <- paste0(matrix_dir, "features.tsv.gz")
matrix.path <- paste0(matrix_dir, "matrix.mtx.gz")
mat <- readMM(file = matrix.path)
feature.names = read.delim(features.path, header = FALSE, stringsAsFactors = FALSE)
barcode.names = read.delim(barcode.path, header = FALSE, stringsAsFactors = FALSE)
colnames(mat) = barcode.names$V1
rownames(mat) = feature.names$V1 
`

Best,
Thomas

**Comment by Hoohm** [comment]
Added your snippet to the documentation to help out other users. Thanks :)

Closing this

**Comment by tiagobrc** [comment]
This solution is great!
