### ISSUE TITLE
--expected_cells option still required when using -wl

### ISSUE THREAD

**Issue by amayer21** [Hoohm/CITE-seq-Count#35]
Hello,

Thanks for developping such usefull tool.

I have some analyses I've done with CITE-seq-Count 1.3.4 that I'm currently rerunning with 1.4.1. I was wondering if it would be possible for the programme to require either `-cells` OR `-wl` as the white list will anyway contains a limited number of droplet barcodes.

The reason for that is that I'm running CITE-seq-Count as part of a bash script that should be able to process different files with different white-lists and I don't want to have to look at the number of lines in each of these white-list and have to encode that number manually for each in the script. I tried to make the script extract this info from the WhiteList file but it didn't work.

Thank you very much

Best wishes,

Alice

PS: It also took me a bit of time finding which option I needed to use to replace the `-hd` option that I had been using in my previous script. I think it would be useful to have that info in the documentation. For example, it would be usefull to have something like `(previously -hd)` written in description of `--max-error`.

**Comment by Hoohm** [comment]
Hello @amayer21,

although I understand the convenience of your request, it poses a small problem for datasets such as 10x where the whitelist is very large (~500'000) but we only expect maybe 20'000 cells.

I will take a look and come back to you next week with a response regarding integration in 1.4.2.

I will also update the documentation concerning the option change from -hd to --max-error.

**Comment by amayer21** [comment]
Hi Hoohm,

Thank you very much for your response. 

For the whitelist, I understand why it's sometimes interesting to use both options together, but if it would be mandatory to use at least one of the option (either -wl or -cells) and possible (but not mandatory) to use both together, it would be great.

Having said that, of course if it's complicated to implement, I'll find a way to count the number of entries in my whitelist to count the expected number of cells and that will solve my problem (I'm working with 10x data but I'm using the barcode file from CellRanger filtered results).

All the best,

Alice

**Comment by Hoohm** [comment]
If a whitelist is given, the output will have all those cells given.

If no whitelist is given, then the top cells (highest umi counts) based on the `-cells` option will be in the output.

**Comment by Hoohm** [comment]
I was thinking about your request again since I'm finishing up on 1.4.2 and I think I might to revert to make `-cells`and `-wl` mutually exclusive again. Mainly because the sparse output will not be affected in size even if you have 3M (latest 10xwhitelist) cells in the whitelist. All the non-existing cells won't be taking any space. The dense matrix will be huge though.

Are you using the sparse output or the dense one?

**Comment by Hoohm** [comment]
I'm gonna leave it like this for now because I don't want to change the defaults too much.

Since in the past `-cells` and `--whitelist` were mutually exclusive and that today sparse matrices are the standard output, if you give a `--whitelist`,  `-cells` will not be used. So you can use `-cells 0` and still get the output based on the whitelist.

**Comment by jdime** [comment]
Hello @Hoohm ,

I'm using **CITE-seq-Count v1.4.2**

I could run the example files (correct_RX.fastq.gz and correct.csv) you provide using `-cells 1`.

But when I try to run my ADH data I get into an error apparently at the 'Finding a whitelist' step. However, I'm aiming to use `-cells`, not to use `-wl` in my run. My run is like this:
`CITE-seq-Count -R1 ~/.../File_R1_001.fastq.gz -R2 ~/...File_R2_001.fastq.gz -t ~/.../FileFlags.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3000 -o MAPPED_WITH_CITE_SEQ_COUNT/
`
From your conversation above, you mention you'll make `-cells` and `-wl` mutually exclusive, but the `--help` displays "Expected number of cells **and** potential whitelist". Does that mean I need to input both parameters? I'm confused because in the correct_* example I didn't need to specify `-wl`

The error looks like this.  Any idea what may be wrong?

Thanks in advance.

> Counting
> 
>  number of reads
> Started mapping
> Processing 22,244,316 reads
> CITE-seq-Count is running with 4 cores.
> Processed 1,000,000 reads in 13.19 seconds. Total reads: 1,000,000 in child 32080
> Processed 1,000,000 reads in 13.17 seconds. Total reads: 2,000,000 in child 32080
> Processed 1,000,000 reads in 37.18 seconds. Total reads: 1,000,000 in child 32081
> Processed 1,000,000 reads in 12.97 seconds. Total reads: 3,000,000 in child 32080
> Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32081
> Processed 1,000,000 reads in 12.42 seconds. Total reads: 4,000,000 in child 32080
> Processed 1,000,000 reads in 1.0 minute, 1.093 seconds. Total reads: 1,000,000 in child 32082
> Processed 1,000,000 reads in 12.65 seconds. Total reads: 3,000,000 in child 32081
> Processed 1,000,000 reads in 12.99 seconds. Total reads: 5,000,000 in child 32080
> Mapping done for process 32080. Processed 5,561,079 reads
> Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32082
> Processed 1,000,000 reads in 12.27 seconds. Total reads: 4,000,000 in child 32081
> Processed 1,000,000 reads in 1.0 minute, 25.12 seconds. Total reads: 1,000,000 in child 32083
> Processed 1,000,000 reads in 13.25 seconds. Total reads: 3,000,000 in child 32082
> Processed 1,000,000 reads in 13.38 seconds. Total reads: 5,000,000 in child 32081
> Mapping done for process 32081. Processed 5,561,079 reads
> Processed 1,000,000 reads in 13.44 seconds. Total reads: 2,000,000 in child 32083
> Processed 1,000,000 reads in 12.88 seconds. Total reads: 4,000,000 in child 32082
> Processed 1,000,000 reads in 13.0 seconds. Total reads: 3,000,000 in child 32083
> Processed 1,000,000 reads in 13.16 seconds. Total reads: 5,000,000 in child 32082
> Mapping done for process 32082. Processed 5,561,079 reads
> Processed 1,000,000 reads in 12.45 seconds. Total reads: 4,000,000 in child 32083
> Processed 1,000,000 reads in 13.12 seconds. Total reads: 5,000,000 in child 32083
> Mapping done for process 32083. Processed 5,561,079 reads
> Mapping done
> Merging results
> Correcting cell barcodes
> Finding a whitelist
> /Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
>   lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
> Traceback (most recent call last):
>   File "/Users/jdiazmej/miniconda3/bin/CITE-seq-Count", line 11, in <module>
>     sys.exit(main())
>   File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 352, in main
>     collapsing_threshold=args.bc_threshold)
>   File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
>     plotfile_prefix=False)
>   File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
>     cell_barcode_counts, cell_number, plotfile_prefix)
>   File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
>     raise ValueError("Something's gone wrong here!!")
> ValueError: Something's gone wrong here!!
>

**Comment by papal22e** [comment]
> Hello @Hoohm ,
> 
> I'm using **CITE-seq-Count v1.4.2**
> 
> I could run the example files (correct_RX.fastq.gz and correct.csv) you provide using `-cells 1`.
> 
> But when I try to run my ADH data I get into an error apparently at the 'Finding a whitelist' step. However, I'm aiming to use `-cells`, not to use `-wl` in my run. My run is like this:
> `CITE-seq-Count -R1 ~/.../File_R1_001.fastq.gz -R2 ~/...File_R2_001.fastq.gz -t ~/.../FileFlags.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3000 -o MAPPED_WITH_CITE_SEQ_COUNT/ `
> From your conversation above, you mention you'll make `-cells` and `-wl` mutually exclusive, but the `--help` displays "Expected number of cells **and** potential whitelist". Does that mean I need to input both parameters? I'm confused because in the correct_* example I didn't need to specify `-wl`
> 
> The error looks like this. Any idea what may be wrong?
> 
> Thanks in advance.
> 
> > Counting
> > number of reads
> > Started mapping
> > Processing 22,244,316 reads
> > CITE-seq-Count is running with 4 cores.
> > Processed 1,000,000 reads in 13.19 seconds. Total reads: 1,000,000 in child 32080
> > Processed 1,000,000 reads in 13.17 seconds. Total reads: 2,000,000 in child 32080
> > Processed 1,000,000 reads in 37.18 seconds. Total reads: 1,000,000 in child 32081
> > Processed 1,000,000 reads in 12.97 seconds. Total reads: 3,000,000 in child 32080
> > Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32081
> > Processed 1,000,000 reads in 12.42 seconds. Total reads: 4,000,000 in child 32080
> > Processed 1,000,000 reads in 1.0 minute, 1.093 seconds. Total reads: 1,000,000 in child 32082
> > Processed 1,000,000 reads in 12.65 seconds. Total reads: 3,000,000 in child 32081
> > Processed 1,000,000 reads in 12.99 seconds. Total reads: 5,000,000 in child 32080
> > Mapping done for process 32080. Processed 5,561,079 reads
> > Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32082
> > Processed 1,000,000 reads in 12.27 seconds. Total reads: 4,000,000 in child 32081
> > Processed 1,000,000 reads in 1.0 minute, 25.12 seconds. Total reads: 1,000,000 in child 32083
> > Processed 1,000,000 reads in 13.25 seconds. Total reads: 3,000,000 in child 32082
> > Processed 1,000,000 reads in 13.38 seconds. Total reads: 5,000,000 in child 32081
> > Mapping done for process 32081. Processed 5,561,079 reads
> > Processed 1,000,000 reads in 13.44 seconds. Total reads: 2,000,000 in child 32083
> > Processed 1,000,000 reads in 12.88 seconds. Total reads: 4,000,000 in child 32082
> > Processed 1,000,000 reads in 13.0 seconds. Total reads: 3,000,000 in child 32083
> > Processed 1,000,000 reads in 13.16 seconds. Total reads: 5,000,000 in child 32082
> > Mapping done for process 32082. Processed 5,561,079 reads
> > Processed 1,000,000 reads in 12.45 seconds. Total reads: 4,000,000 in child 32083
> > Processed 1,000,000 reads in 13.12 seconds. Total reads: 5,000,000 in child 32083
> > Mapping done for process 32083. Processed 5,561,079 reads
> > Mapping done
> > Merging results
> > Correcting cell barcodes
> > Finding a whitelist
> > /Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
> > lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
> > Traceback (most recent call last):
> > File "/Users/jdiazmej/miniconda3/bin/CITE-seq-Count", line 11, in 
> > sys.exit(main())
> > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/**main**.py", line 352, in main
> > collapsing_threshold=args.bc_threshold)
> > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
> > plotfile_prefix=False)
> > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
> > cell_barcode_counts, cell_number, plotfile_prefix)
> > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
> > raise ValueError("Something's gone wrong here!!")
> > ValueError: Something's gone wrong here!!

Were you able to solve the error? I am having the same issue right now and was wondering what the issue might be.

Thanks,
Efi

**Comment by jdime** [comment]
> > Hello @Hoohm ,
> > I'm using **CITE-seq-Count v1.4.2**
> > I could run the example files (correct_RX.fastq.gz and correct.csv) you provide using `-cells 1`.
> > But when I try to run my ADH data I get into an error apparently at the 'Finding a whitelist' step. However, I'm aiming to use `-cells`, not to use `-wl` in my run. My run is like this:
> > `CITE-seq-Count -R1 ~/.../File_R1_001.fastq.gz -R2 ~/...File_R2_001.fastq.gz -t ~/.../FileFlags.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3000 -o MAPPED_WITH_CITE_SEQ_COUNT/ `
> > From your conversation above, you mention you'll make `-cells` and `-wl` mutually exclusive, but the `--help` displays "Expected number of cells **and** potential whitelist". Does that mean I need to input both parameters? I'm confused because in the correct_* example I didn't need to specify `-wl`
> > The error looks like this. Any idea what may be wrong?
> > Thanks in advance.
> > > Counting
> > > number of reads
> > > Started mapping
> > > Processing 22,244,316 reads
> > > CITE-seq-Count is running with 4 cores.
> > > Processed 1,000,000 reads in 13.19 seconds. Total reads: 1,000,000 in child 32080
> > > Processed 1,000,000 reads in 13.17 seconds. Total reads: 2,000,000 in child 32080
> > > Processed 1,000,000 reads in 37.18 seconds. Total reads: 1,000,000 in child 32081
> > > Processed 1,000,000 reads in 12.97 seconds. Total reads: 3,000,000 in child 32080
> > > Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32081
> > > Processed 1,000,000 reads in 12.42 seconds. Total reads: 4,000,000 in child 32080
> > > Processed 1,000,000 reads in 1.0 minute, 1.093 seconds. Total reads: 1,000,000 in child 32082
> > > Processed 1,000,000 reads in 12.65 seconds. Total reads: 3,000,000 in child 32081
> > > Processed 1,000,000 reads in 12.99 seconds. Total reads: 5,000,000 in child 32080
> > > Mapping done for process 32080. Processed 5,561,079 reads
> > > Processed 1,000,000 reads in 13.11 seconds. Total reads: 2,000,000 in child 32082
> > > Processed 1,000,000 reads in 12.27 seconds. Total reads: 4,000,000 in child 32081
> > > Processed 1,000,000 reads in 1.0 minute, 25.12 seconds. Total reads: 1,000,000 in child 32083
> > > Processed 1,000,000 reads in 13.25 seconds. Total reads: 3,000,000 in child 32082
> > > Processed 1,000,000 reads in 13.38 seconds. Total reads: 5,000,000 in child 32081
> > > Mapping done for process 32081. Processed 5,561,079 reads
> > > Processed 1,000,000 reads in 13.44 seconds. Total reads: 2,000,000 in child 32083
> > > Processed 1,000,000 reads in 12.88 seconds. Total reads: 4,000,000 in child 32082
> > > Processed 1,000,000 reads in 13.0 seconds. Total reads: 3,000,000 in child 32083
> > > Processed 1,000,000 reads in 13.16 seconds. Total reads: 5,000,000 in child 32082
> > > Mapping done for process 32082. Processed 5,561,079 reads
> > > Processed 1,000,000 reads in 12.45 seconds. Total reads: 4,000,000 in child 32083
> > > Processed 1,000,000 reads in 13.12 seconds. Total reads: 5,000,000 in child 32083
> > > Mapping done for process 32083. Processed 5,561,079 reads
> > > Mapping done
> > > Merging results
> > > Correcting cell barcodes
> > > Finding a whitelist
> > > /Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
> > > lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
> > > Traceback (most recent call last):
> > > File "/Users/jdiazmej/miniconda3/bin/CITE-seq-Count", line 11, in
> > > sys.exit(main())
> > > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/**main**.py", line 352, in main
> > > collapsing_threshold=args.bc_threshold)
> > > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
> > > plotfile_prefix=False)
> > > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
> > > cell_barcode_counts, cell_number, plotfile_prefix)
> > > File "/Users/jdiazmej/miniconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
> > > raise ValueError("Something's gone wrong here!!")
> > > ValueError: Something's gone wrong here!!
> 
> Were you able to solve the error? I am having the same issue right now and was wondering what the issue might be.
> 
> Thanks,
> Efi

The  `-cells` option didn't work for me, so I worked around.

I passed a file "list_of_barcodes_from_rna.csv" with the "filtered" list of barcodes detected in the RNA measurements (one barcode per line), like:
AAACGGGTCTGGTTCC-1
AAAGATGCAAAGGAAG-1
AAAGATGCATCCCATC-1

And used something like:
`cells 0 -wl ~/path_to/list_of_barcodes_from_rna.csv`

Cheers,

**Comment by papal22e** [comment]
Thanks for the reply, I am trying this as we speak!

**Comment by Hoohm** [comment]
Hello everybody,
this bug is fixed on the develop branch and will be implemented in the next version.
The fix proposed by others here is valid as well.

I have no release date yet for this version sorry.

**Comment by Hoohm** [comment]
Bug should be fixed in the new 1.4.3 release. Feel free to reopen if it's not.
