### ISSUE TITLE
ERROR:root:No local minima was accepted

### ISSUE THREAD

**Issue by amayer21** [Hoohm/CITE-seq-Count#36]
Hello,
I'm trying to run CITE-seq-Count 1.4.1 on data I already analysed with the 1.3.4 and it doesn't work in my hands. It starts processing reads then after processing 850,716 reads, it throw the following error: 
```
ERROR:root:No local minima was accepted. Recommend checking the plot output and counts per local minima (requires `--plot-prefix` option) and then re-running with manually selected threshold (`--set-cell-number` option)
```
Despite this error, the programme keep running (without processing any more reads and without generating any output files) until it was killed (after 1h33 or 33min) by the system because it was using too much memory.

I tried twice with the command
```
CITE-seq-Count -R1 ${R1file} -R2 ${R2file} -t ${TagsFile} -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 15291 -wl ${BClist} --max-error 1 -o ${OutputDir}
```

I can't find the option `--set-cell-number` in the documentation, so I don't know what to do.

Could you help me with this?

You'll find the script I used and the log file here attached.
[CiteSeqCount.3410940.log](https://github.com/Hoohm/CITE-seq-Count/files/2841624/CiteSeqCount.3410940.log)
[CiteSeqCount_script.txt](https://github.com/Hoohm/CITE-seq-Count/files/2841674/CiteSeqCount_script.txt)

Thank you very much,
Best wishes,
Alice

**Comment by amayer21** [comment]
Just as a matter of comparison, the version 1.3.4 processed the 13,611,276 reads of the same fastq.gz file in less than 4 minutes (using the same input file and the same whiteList)

**Comment by r-mvl** [comment]
Hello,

I am having the same problem... any idea how to solve this? @Hoohm 

Many thanks

**Comment by Hoohm** [comment]
Hello @r-mvl  and @amayer21 
This error comes from umi_tools which is used to correct cell barcodes. This is why you don't see the options. I have to yet to modify it so that you don't have to run the script twice if this error arises.

Could you please try and use the develop branch, it should fix the issue of never finishing the umi correction. If it still runs for too long, please use the option `--no_umi_correction` to deactivate the umi correction while I fix it for the next release.

This is how you install and use the develop branch:

```
git clone https://github.com/Hoohm/CITE-seq-Count.git
cd CITE-seq-Count
git checkout develop
python3.6 setup.py develop
```

If you type: `CITE-seq-Count --version` you should get 1.4.2

**Comment by amayer21** [comment]
Hi Hoohm,
Thanks for your reply. 
I have to focus on another project just now but should have more data to analyse at some point. If the new version is not out then, I'll use the develop branch.
All the best,
Alice

**Comment by wflynny** [comment]
@Hoohm I ran into the same problem described here using version 1.4.1.  Installing via

```{bash}
$ git clone git@github.com:Hoohm/CITE-seq-Count.git -b develop
$ cd CITE-seq-Count
$ python setup.py develop
```

correctly gave me 
```{bash}
$ CITE-seq-Count --version
CITE-seq-Count v1.4.2
```

Rerunning and it no longer hangs nor gives me the `No local minima...` line and I _think_ the output looks good.

**Comment by Hoohm** [comment]
Great!
Happy to hear that. Would you mind telling me if you got any "bad" cells in the report. Yaml?

**Comment by wflynny** [comment]
I did, 19.  I'm also concerned about the high percentage of unmapped reads.  Below is the report:
```
Date: 2019-02-21
Running time: 1.0 hour, 13.0 minutes, 21.96 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 18229352
Percentage mapped: 80
Percentage unmapped: 20
Bad cells: 19
Correction:
	Cell barcodes collapsing threshold: 1
	Cell barcodes corrected: 86173
	UMI collapsing threshold: 2
	UMIs corrected: 484728
Run parameters:
	Read1_filename: /path/to/R1_001.fastq.gz
	Read2_filename: /path/to/R2_001.fastq.gz
	Cell barcode:
		First position: 1
		Last position: 16
	UMI barcode:
		First position: 17
		Last position: 28
	Expected cells: 12000
	Tags max errors: 3
	Start trim: 0
```

**Comment by Hoohm** [comment]
19 cells is not that high over 12000.
What are the top unknown tags you get in those 20%?

**Comment by wflynny** [comment]
Most of the top unknown tags are 98bp of straight PolyA's.  For example:
```
tag,count
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,5036
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC,852
ACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC,252
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,242
AAGCAGTGGTATCAACGCAGAGTACATGGGGAGGCATTCAGGCAGCGAGAGCAGAGCAGCGTAGAGCAGCACAGCTGAGCTCGTGAGGCAGGAGACTC,187
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,183
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,160
AAGCAGTGGTATCAACGCAGAGTACATGGGAGGCATTCAGGCAGCGAGAGCAGAGCAGCGTAGAGCAGCACAGCTGAGCTCGTGAGGCAGGAGACTCA,147
AAGCAGTGGTATCAACGCAGAGTACATGGGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,132
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAA,119
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,109
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAA,105
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAA,95
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAA,95
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAA,94
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAA,93
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAA,93
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAA,91
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAA,88
```

**Comment by Hoohm** [comment]
Hi @wflynny 
the error should not pop up anymore. however, umi_tools 1.0.0 came with a new method and some users report another error from the whitelist generation.

I have changed this on the develop branch, can you test it out?

Another possibility is to use the raw list of 10x cell barcodes instead of trying to find a new one derived from the HTO/ADT data.

This is actually better because knowing the list in advance means we are sure about the correction we can apply to the unknown cells.

**Comment by Hoohm** [comment]
Hello @amayer21 
I'm wrapping up issues for a new release. I'm closing this for now. Feel free to reopen if needed.
