### ISSUE TITLE
job exceeded memory limit

### ISSUE THREAD

**Issue by amayer21** [Hoohm/CITE-seq-Count#37]
Hello,

Sorry to open several different issue... I try to open 1 issue per problem so that each can be closed when solved, independently of the others...

As explained in issue #36, I'm running CITE-seq-Count 1.4.1 on data previoulsy analysed with 1.3.4. 

I've tried twice and in both cases, the programme has been killed by the system because it was using too much memory. I'm running it on a cluster, using the job manager slurm and I have to tell slurm how much memory to allocate to my script. Is there a way to limit the memory used by CITE-seq-Count? And is-there a way to know how much it will need? In this case I allocated 15Gb and it was killed once after 1h30 and the second time after 33 minutes.

Here is the error message:
```
slurmstepd: Job 3410940 exceeded memory limit (15912452 > 15728640), being killed
```
You'll find the script and log file attached to the issue #36.

Thank you very much,

Best wishes,

Alice

**Comment by Hoohm** [comment]
Hello @amayer21 
the amount of memory needed by the script will change based on a few different things
1) How many reads are being processed
2) How many TAGS are being searched for
3) How many threads you use, the overhead from each thread will demand a bit more memory.

Until now I have always asked for way more on my cluster to be sure it would be processed.

How many reads are you processing?
I will run some data with different values and give a rule of thumb of how much memory is required. I can't promise any dates right as I am working on other projects.

**Comment by amayer21** [comment]
Hello Hoohm,
Thank for your reply. 
I had 13.6M reads and about 15,291 expected cells (whitelist with 15,291 barcodes).
I will try to downsample both to test the memory needed next time I need to analyse HTO data. 

This one was a preliminary experiment we have to present to our scientific advisory board tomorrow so I used the results generated using a previous version of CITE-seq-Count (and the corelation with results obtain with genetic demultiplexing with Demuxlet was already very good).
This is a great tool! Thanks for developing and maintening it!
All the best,
Alice

**Comment by Hoohm** [comment]
Hello @amayer21 

I suspect part of the problem came from the UMI correction. Can you try to rerun it now with 1.4.2 and let me know if you still have too much memory being used?

**Comment by amayer21** [comment]
Hello Patrick,
I’m sorry I didn't manage to rerun this week. Will try to do it asap and will let you know when done.
Thank you very much for your help
Alice

**Comment by aifi-aldan** [comment]
Picking up where this ticket left off.

We were able to get to the the whitelist generation step while running on 1.4.2, though we were unfortunately hit by the whitelist generation bug noted in #48 [1], caused in part by the shift over to use umi_tools. We then upgraded to the develop branch version 1.4.3 and reran with the following parameters [2], only to encounter OOM errors late into the job [3].

Both runs intended to process 40,334,657 reads, and ran alone on instances with 96 cores, 624GB ram.

We intend to do another run with '-T 48' to see if this alleviates issues. Does this sound reasonable? We're happy to grab some diagnostics if you'd like them, just let us know what you'd like to see.

[1] -
`Mapping done for process 26683. Processed 420,152 reads
Mapping done for process 26684. Processed 420,217 reads
Mapping done
Merging results
Correcting cell barcodes
Finding a whitelist
/usr/lib64/python3.6/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
  lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
Traceback (most recent call last):
  File "/bin/CITE-seq-Count", line 11, in <module>
    load_entry_point('CITE-seq-Count==1.4.2', 'console_scripts', 'CITE-seq-Count')()
  File "/usr/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 352, in main
    collapsing_threshold=args.bc_threshold)
  File "/usr/lib/python3.6/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
    plotfile_prefix=False)
  File "/usr/lib64/python3.6/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
    cell_barcode_counts, cell_number, plotfile_prefix)
  File "/usr/lib64/python3.6/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
    raise ValueError("Something's gone wrong here!!")
ValueError: Something's gone wrong here!!
srun: error: hpc-compute1: task 0: Exited with exit code 1`

[2] -
`srun CITE-seq-Count \
-R1 /data/merged_fastq/Pool-16-HTO/Pool-16-HTO_S01_L003_R1_001.fastq.gz \
-R2 /data/merged_fastq/Pool-16-HTO/Pool-16-HTO_S01_L003_R2_001.fastq.gz \
-t /data/CellHashHTO/miSeq_TAG.csv \
-cbf 1 \
-cbl 16 \
-umif 17 \
-umil 28 \
-cells 9704 \
--max-error 1 \
-o /data/CellHashHTO/Pool-16-HTO \
-T 84`

[3]-
`Mapping done for process 82666. Processed 480,174 reads
Mapping done for process 82667. Processed 480,174 reads
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/site-packages/multiprocess/pool.py", line 479, in _handle_results
    cache[job]._set(i, obj)
  File "/usr/lib64/python3.6/site-packages/multiprocess/pool.py", line 651, in _set
    self._error_callback(self._value)
TypeError: '_io.TextIOWrapper' object is not callable

Mapping done for process 82673. Processed 480,174 reads
srun: Force Terminated job 38495
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** STEP 38495.0 ON hpc-compute1 CANCELLED AT 2019-07-17T01:27:56 ***
slurmstepd: error: Detected 18819 oom-kill event(s) in step 38495.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: hpc-compute1: task 0: Out Of Memory`

**Comment by aifi-aldan** [comment]
Thankfully, halfing the amount of allocated CPU was able to help us push past the OOM errors.

**Comment by Hoohm** [comment]
That's great @amayer21.
Error [1] should be now fixed with 1.4.3 being officially out!
Feel free to reopen if needed.

**Comment by LKremer** [comment]
Hi @Hoohm ,
is it safe to ignore error [3]? I'm getting the exact same error on CITE-seq-Count v1.4.3, but the program keeps running. I found that the error doesn't occur when I run CITE-seq-Count on a single thread, so it might be an issue with multiprocessing as the error message also suggests.

**Comment by aifi-aldan** [comment]
Our path to resolution simply involved cutting down on the amount of allocated CPUs. You can specify this as well in your command via the -T flag.
