### ISSUE TITLE
Best way to count ADT tags ?

### ISSUE THREAD

**Issue by Mr-Laurent** [Hoohm/CITE-seq-Count#38]
Hello, 

I recently had some CITE-seq data to analyze and as a beginner, I'm really grateful for your CITE-seq-Count workflow.
It's working well for my HTO labeling because the sequence looks like what we expect in the R2: **[HTO Barcode]**-[CGT]-poly A
with only a few errors, but my ADT labeling is not in the same shape : 
(polynucleotide sequence of 0 to 21 nt)-**[ADT Barcode]**-[CGT]-poly A

As it's mostly a 21nt sequence before and that there is no Regex option,  I can use the `-trim=21` option, but I lose a lot of counts. 
So then I thought that as the 21nt sequence is always the same, I can use it in the csv listing the tags, like :  
[ADT Barcode],CD3
G[ADT Barcode],CD3
GG[ADT Barcode],CD3
ACGG[ADT Barcode],CD3
TACGG[ADT Barcode],CD3
... and so on. 
But  I don't think it's a sustainable solution... 
Do you have any better solution to advise me on this issue?

**Comment by Hoohm** [comment]
Hello @Mr-Laurent 

Your solution should work although I would use 0 for `--max-error`.
Right now I don't have a good solution for you using CITE-seq-Count directly. One solution would be to use a trimming tool such as cutadapt on R2 to get rid of the constant sequence and then run CITE-seq-Count.

Could you try this and let me know?
If it is still not working as expected, I might look into implementing a sliding windows for this purpose using something like [this](https://gist.github.com/Hoohm/ddf7754b1eed8ccf2c556b7969799c3a)

**Comment by Hoohm** [comment]
Hi @Mr-Laurent 
I'm working on version 1.4.2 and am testing some modification that would allow for your data to work as well.

Would you be able to send me a sample to test it on?

**Comment by Mr-Laurent** [comment]
Hi, @Hoohm 
In a very recent turn of events, we investigated why the results gave us so little UMI counts per cells on our ADT and we found out that we had a misunderstanding with the sequencing platform that didn't took into account the CITE-seq index for ADT (some were merged with the transcript data, and the vast majorty was in the bin as "Undetermined") which explained why they were not looking great in the FASTQ file I was using for Cite-Seq-Count, as well as the low UMI count.

They de-multiplexed again with the appropriate index, and this time the sequences are as expected. 
I'm not finished yet with the data analysis, but for the Cite-Seq-Count part, I have good results which is really reassuring ! 
(And I guess you can close the issue here )

For the sample, I'll ask to my supervisor and i'll recontact you by mail to tell you

**Comment by Hoohm** [comment]
Hello @Mr-Laurent 
in the meantime I implemented a sliding window in the alignement. You can use it with the option: `--sliding-window`

**Comment by Hoohm** [comment]
Closing this for now. Feel free to reopen if you need to.
