### ISSUE TITLE
citeseq count is returning negative count values

### ISSUE THREAD

**Issue by Munfred** [Hoohm/CITE-seq-Count#40]
Hello, I'm running into a very odd issue where some of the entries in the hashtag count matrix are **negative**. Below are some examples of the numbers I see.

![image](https://user-images.githubusercontent.com/12504176/52913087-43194900-326f-11e9-88a7-cc0686a712e5.png)

I couldn't attach all the output files and the notebook I used to generate them, so I've put them in this google drive folder:

https://drive.google.com/open?id=1guoYnF4-whi_0aUgGQeugQ966bFBoc_J

This aberrant count matrix was generated with the following call:
```
CITE-seq-Count -R1 /home/munfred/hashing/data/SRR8281307_1.fastq.gz -R2 /home/munfred/hashing/data/SRR8281307_2.fastq.gz \
-t ./HTOs_len13.csv -cbf 1 -cbl 16 -umif 17 -umil 26 \
-o ./citeseqcount1 -cells 500000
```

`SRR8281307` is the RNA HTO dataset from the hashtag paper: https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP127179

Additionally, I have one more question: can you confirm that the UMI bug has been fixed? I have done the installation with the command `pip install CITE-seq-Count==1.4.1`

However, after running ` CITE-seq-Count` on the SRR8281307 data, I get back a matrix with 71,195,205 entries. This is suspiciously close to the 74,219,921  entries in the original fastq file, and suggests to me that the UMIs are not being collapsed. I have looked into both `read_count` and `umi_count` folder contents and they are identical.

**Comment by Munfred** [comment]
Hello, I think I found the cause of the negative numbers. Int overflow. I noticed that the maximum values of hashtags were suspiciously close to 32768, (as you can see on the table below) which is the maximum value supported by numpy int16: https://het.as.utexas.edu/HET/Software/Numpy/reference/generated/numpy.iinfo.html

![image](https://user-images.githubusercontent.com/12504176/52929144-02b1dd80-32f8-11e9-919f-3a97ce75fcce.png)


I did a quick search on the repo scripts, and I think I found the offending lines, 250 and 251 on `processing.py`:

https://github.com/Hoohm/CITE-seq-Count/blob/7e8b5f068b578424a6a518e9b81d77cd3eee3463/cite_seq_count/processing.py#L249-L250

If you change them to use `dtype=int32` that should fix the issue

**Comment by Hoohm** [comment]
Hello @Munfred and thanks for the catch!
I think this might also be linked to the other major issue that hangs the umi correction. I'm working on an update that should come out this week that will include the 16->32 fix and probably the umi correction issue fixed.

**Comment by Munfred** [comment]
Hi, I just wanted to give you an update I forgot to do earlier

The reason why I was running CITE-seq-Count on the cell hashing dataset is because I wanted to compare it's results with a different demultiplexing approach that uses kallisto. 

I have finished a forst prototype of the pipeline on a jupyter notebook and it agrees quite nicely with the results from CITE-seq-Count when I make the confusion matrix. 

You can see the jupyter notebook and some explanation of the workflow here: https://github.com/pachterlab/kite


I also made a poster explaining it if you are curious:
https://drive.google.com/file/d/1TKyjlFvHwwxfF7UqPn_-LMl7TBavp9Xm/view?usp=drivesdk

**Comment by Hoohm** [comment]
Hey @Munfred,
thanks for the heads up and the poster.
Happy to see that results are matching nicely :)

Is this the new "sircel" or is it totally different from this project?

**Comment by Munfred** [comment]
Hi, sorry for the delay.

This is unrelated to sircel, was a result of the new `kallisto bus` feature that let's kallisto process single cell datasets from various technologies. 

More info about the BUS format can be found here: https://bustools.github.io/

Some example workflows in python for processing single cell datasets are here: https://github.com/BUStools/BUS_notebooks_python

**Comment by Hoohm** [comment]
This is interesting. I might look into it and use it for dropSeqPipe!

Thanks for the heads up :)

Closing this as the bug was fixed
