### ISSUE TITLE
TAG file error

### ISSUE THREAD

**Issue by mcorley5** [Hoohm/CITE-seq-Count#41]
I receive the following error now:

This tag ﻿TGATGGCCTATTGG is not only composed of ATGC bases.
Please check your tags file
Exiting the application.

**Comment by Hoohm** [comment]
Well that is definitely an odd thing to witness.
![image](https://user-images.githubusercontent.com/1267560/53402668-774ce200-39b2-11e9-933d-46412b17830a.png)
When I copy your text to test it on https://regex101.com/ I see an added dot before the tag.

If I try to identify this dot using http://www.babelstone.co.uk/Unicode/whatisit.html I get:
`U+FEFF : ZERO WIDTH NO-BREAK SPACE [BOM] {BOM, ZWNBSP}`

**Comment by mcorley5** [comment]
I was utilizing the same .csv that I had used previously.
I ended up regenerating the file and it seems to have fixed the issue.
Very odd indeed.

**Comment by LineWulff** [comment]
Did you ever figure out why this error occur? I have the same issue and I can see the dot when I copy it in to the regex101 page.

**Comment by Lopiniatre** [comment]
I got the same error and weird U+FEFF presence on a .csv file created through excel. I manually recreated the file through the vi command line editor and it worked. Probably something added by Excel even though it's saved as .csv?
