### ISSUE TITLE
how to cite cite-seq count

### ISSUE THREAD

**Issue by ivonyao** [Hoohm/CITE-seq-Count#44]
Just a lazy question, just wondering how to cite cite-seq count in publication?
Didn't found preferred cited articles, just want to make sure using the right acknowledgement. The orignial cite-seq paper?
Thanks

**Comment by Hoohm** [comment]
Hello @ivonyao 
this is a good question and will be added in the documentation for the next release. In the meantime, here is the DOI you can use.
[![DOI](https://zenodo.org/badge/99617772.svg)](https://zenodo.org/badge/latestdoi/99617772)

**Comment by Hoohm** [comment]
i just made it so maybe it takes some time to activate.

**Comment by Hoohm** [comment]
I've added this to the documentation now. Closing this
