### ISSUE TITLE
Stuck at "Testing cell barcode collapsing threshold..."

### ISSUE THREAD

**Issue by zakiF** [Hoohm/CITE-seq-Count#46]
Hi,

With the recent version (1.4.2), it seems I am unable to get pass the stage of ;

> Testing cell barcode collapsing threshold of 1

I used the following commands to initially test the workflow 

`python3 CITE_seq_Count \
	-R1 test/HTO_R1.fastq.gz \
	-R2 test/HTO_R2.fastq.gz \
	-t test/tags.csv \
	-cbf 1 -cbl 16 \
	-umif 17 -umil 26 \
	-cells 100 \
	-wl test/CellBarcode_GEM_01_1Reads.txt \
	-o CITE_seq_output_GEM01 \
	--no_umi_correctio \
	-n 100 `

I uploaded the example file [here](https://www.dropbox.com/sh/emcjg6o64x4ahf0/AADgzJQiM5YQOwKB5s7ojjAea?dl=0) in case it would help.

Strangely this only happens with the current version? I ran the previous version okay.

Best
Zaki

**Comment by Hoohm** [comment]
Hello @zakiF 
when you mean stuck, how long would this be? This is a new step I included to double check that the proposed collapsing distance of cell barcodes is not over the actual distance between cells in a given whitelist.
It can take up to a few minutes depending on how big the list is and how fast your cpu is. It's testing all pairs of barcodes distances.

**Comment by zakiF** [comment]
Hi @Hoohm ,

Thanks for the reply. I'l leave it running a bit longer with the full dataset and will let keep you informed. I managed to run the example with -n 100.  Now I am running with the whole dataset. 

Thanks for the reply and will let you know

**Comment by Hoohm** [comment]
This step is not influenced by how many reads you process. This is done on the whole given whitelist beforehand.

**Comment by zakiF** [comment]
I see, thanks for the input. I think it's safe to close the issue since I think if I leave it running the code will finish.

**Comment by happar73** [comment]
@zakiF @Hoohm I ran the same issue, it took more than 3 hours and still stucked there. I reran it, and got the results. How to fix it? Many thanks.
