### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by JamesCotterell** [Hoohm/CITE-seq-Count#47]
when using:
sudo pip install CITE-seq-Count==1.4.2 --no-cache-dir

I get:
Could not find a version that satisfies the requirement CITE-seq-Count==1.4.2 (from versions: 1.2)
No matching distribution found for CITE-seq-Count==1.4.2

**Comment by Hoohm** [comment]
Hello @JamesCotterell 

I'm not sure, it might be related to your pip/python version. 1.2 was compatible with python2.7, 1.4.2 is only compatible with python 3.6 and higher.

**Comment by JamesCotterell** [comment]
that fixed it..great thanks!

**Comment by jshrivastava** [comment]
Cannot install even with python3.6. When I give command 
sudo -H pip3 install CITE-seq-Count==1.4.2 --no-cache-dir

I am getting the error:   RuntimeError: Python version >= 3.5 required.

when I checked python version -python -V
It gives me Python 3.6.3.

Please suggest.
