### ISSUE TITLE
Error messages or no output when running CITE-seq-Count 1.4.2 with specific options

### ISSUE THREAD

**Issue by rhduerr** [Hoohm/CITE-seq-Count#49]
I was able to successfully run the latest release of CITE-seq-Count (version 1.4.2) with the required -cells parameter, but without the -wl, --bc_collapsing_dist, --umi_collapsing_dist, or --max-error options.  However, when I tried to run it with --umi_collapsing_dist 1 and --max-error 1  options, the following error messages appeared after mapping was done:
Mapping done
Merging results
Correcting cell barcodes
Finding a whitelist
Traceback (most recent call last):
  File "/ihome/crc/install/cite-seq-count/python3.7/bin/CITE-seq-Count", line 11, in <module>
    sys.exit(main())
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 352, in main
    collapsing_threshold=args.bc_threshold)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
    plotfile_prefix=False)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
    cell_barcode_counts, cell_number, plotfile_prefix)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
    raise ValueError("Something's gone wrong here!!")
ValueError: Something's gone wrong here!!

When I tried to run CITE-seq-Count version 1.4.2 with the -wl option to provide the 10x Genomics 737K-august-2016.txt cell barcode whitelist, I was concerned that something was wrong with that run too because it was going for 75+ minutes and there was no output in the log file (not even an indication that reads were being counted, mapped and processed), so I canceled that run.

**Comment by zakiF** [comment]
Just to mention I had a similar issue with the version (1.4.2) where I provided the full list of 737K barcode via the parameter ; 

`-wl 737K-august-2016.txt`

The program ran for 2 days after which I killed it. 

When I ran it with only a select set of barcode (barcode which have at least 1 hashtag sequencing reads,  n=84,667). The program managed to finish (I'l double check how long it took). 

Reference issue #46

**Comment by Hoohm** [comment]
I had similar issues when running on full raw lists. I'm deactivating this feature for next release and put the burden of having a clean list to the user as well as keeping the default distance of 1.

if I find an efficient way of doing this with long lists, I'll add it again.

**Comment by rhduerr** [comment]
My workaround to the lack of output when I attempted to run CITE-seq-Count 1.4.2 using -wl 737K-august-2016.txt was to:
1) run CITE-seq-Count 1.4.2 without the -wl option,
2) identify the intersection between the barcodes listed in the umi_count output from #1 and the 737K-august-2016.txt whitelist, and 
3) rerun CITE-seq-Count 1.4.2 with the -wl option and using the intersection from #2 as a whitelist.

**Comment by j0ntt** [comment]
> I had similar issues when running on full raw lists. I'm deactivating this feature for next release and put the burden of having a clean list to the user as well as keeping the default distance of 1.
> 
> if I find an efficient way of doing this with long lists, I'll add it again.

Does a clean list mean for example the filtered barcode list from Cellranger, i.e. those that have been identified as cells by Cellranger?

**Comment by Hoohm** [comment]
Yes this would qualify as a clean list.
