### ISSUE TITLE
cell-hashing pipeline questions

### ISSUE THREAD

**Issue by bio-la** [Hoohm/CITE-seq-Count#5]
Hi,
maybe this is not the right place to ask, but I seem to be unable to get a response on the [cite-seq](https://cite-seq.com/computational-tools/) website and I would really appreciate if you could comment on the following.
I'm about to do a cell hashing with some 10x libraries.

Can you please confirm that the sequencing cycles configuration of the Hashing libraries can be the same of a 10x library? From your script it seems so, as it will look for the classic coordinates of the CellBarcode(1-16) UMI-(17-26) and so on. (Of course, if it was dropseq beads i'd have to use a different sequencing configuration)

Also, in the preprint of the hashing, in the methods : "Fastq files from the 10x libraries with four distinct barcodes were pooled together and processed using the standard Drop-seq pipeline". If you have fastq to start with it means you basecalled them with the 10x pipeline?
Can I  basecall with the cellranger wrapper or do you suggest any other way? (the dropseq paper suggested a couple of other ways, so I'm really just checking what's the best practice)
and then I have to handle the alignment and following steps exactly as in Dropseq pipeline, right?

Any suggestion would be really welcome! And many thanks for such amazing tool.

Best,
biola

**Comment by bio-la** [comment]
Hi @Hoohm, thanks for your reply,
Sorry if my message was unclear.

The hashing experiment consists of a pool of different samples which were incubated with the different oligo-conjugated antibodies, so this multiplexed pool is loaded into one 10x channel. if I generate >1 different pools, (using >1 channels) each of them will have its separate 10x index(es, as those are 4). My sequencer will produce the basecall files for those n>=1 libraries. From the 10x website:

"The cellranger workflow starts by demultiplexing the Illumina sequencer's base call files (BCLs) for each flowcell directory into FASTQ files. 10x recommends using cellranger mkfastq, a pipeline that wraps Illumina's bcl2fastq and provides a number of convenient features in addition to the features of bcl2fastq"

Hence my question, and I assume the answer is yes, I can do base calling with the 10x wrapper and this will handle the demultiplexing of the library indexes. this is just the "outside" demultiplexing, the one that deconvolutes the libraries produced from n>=1 10x channels .

At this stage, I have 3 fastqs for each library (R1,R2, Index). The 10x pipeline would continue with cellranger count, which does the alignment and the feature counting (producing the gene count matrices).

The goal of this analysis is to produce 1) a gene count matrix and 2) a list of the best possible antibodies which were incubated with the multiplexed samples and will deconvolute back, for each library, the multiple samples. (the hashing demultiplexing)

I'm assuming it wouldn't make a difference if I now produced the count matrix with the 10x pipeline, or if I used these Fastq files as the input to the drop seq pipeline- which is what you did given what I get from the paper? What did you use? 
I just don't understand what you mean by _This probably refers to the 10x indexes. You should pool them together if you run the data on another pipeline than cell ranger._ furthermore, this makes the sentence that I quoted from the paper even more obscure. :/

Once I have a list of good barcodes from the count matrix, whatever the way I generated it, I can use this to speed up the cell-hashing demultiplexing (your script) which requires the same fastqs as before (R1 and R2).

Is my interpretation of the flow correct, or can you give me a list of steps cause the paper doesn't really say much?
thank you!

**Comment by Hoohm** [comment]
Hello @bio-la 

> I can do base calling with the 10x wrapper and this will handle the demultiplexing of the library indexes

Yes, this is fine.

Now I have a question. How many different files do you get for one sample? 3 or 6? You should have 3 files from the mRNA and 3 files from the TAG sequences. Right?

**Comment by bio-la** [comment]
Hi @Hoohm ,

you lost me here. are you talking about fastq files per sample? in a normal scenario it's 3 fastq files. if after the cite-seq script then produces 3 other fastq files (from the R1, R2) it's something that I don't know (and it doesn't seem to me it's in the described outputs) as I didn't sequence the hashing experiment yet. Could you give me more details please?
thanks!

**Comment by wflynny** [comment]
@bio-la  You should separate the anti-oligo library from the cDNA library prior to sequencing as described in the CITE-seq paper [1], figure S1d.  

If done that way, you can then index the two libraries with different 10X indices, run them in the same lane, then demultiplex via `cellranger mkfastq`, resulting in 3 fastqs (R1, R2, index) from the transcriptome and 3 fastqs (R1, R2, index) from the hashtags.  

Run the first 3 through `cellranger count` to get a digital gene-cell expression matrix.  You can then use the cell barcodes from the transcriptome as a whitelist when running R1, R2 from the hashtags through `CITE-seq-Count` to get a hashtag-cell matrix.  Alternatively, you can use as a whitelist the `cellranger-barcodes-737K-august-2016.txt` that comes included with every cellranger version.

[1]: https://www.nature.com/articles/nmeth.4380

**Comment by oursu-broad** [comment]
Hi,

I have a similar question. I am working with a case where the barcodes I want to count are in read 2, where I also have the reads coming from regular mRNA. 

My question is: 
Is it ok to provide to the CITE-seq count script the fastq files I obtain from running "cellranger mkfastq" (which demultiplexes BCL files into fastq files)? Or should I run bcl2fastq with some specific parameters to obtain the files that the CITE-seq count script expects? To clarify, from "cellranger mkfastq" I am obtaining 3 fastq files (I1, R1 and R2), not 6 files, since both the reads coming from mRNAs and those coming from my barcodes of interest are in the same library.

Thanks,
Oana

**Comment by wflynny** [comment]
@oursu-broad @bio-la, In principle, if you just have a combined 10X library and the 3 fastqs associated with it, I think you should be able to proceed as follows:

1. Run R1, R2, and I1 through cellranger count.  The hashtags shouldn't align and thus those reads will be excluded; note that will subsequently bring down some metrics in the `metrics_summary.csv`.

2. Run R1 and R2 through CITE-seq-Count.  It'll take a long time (due to ~100+ fold more reads depending on your tag loadings), but it should work reasonably well if you specify enough As in the polyA tail portion of your tag regex.  
You may also want to use the resulting counts matrix from the previous step to create a cell whitelist.  Alternatively, if you want to run both in parallel, you can use the cellranger barcode whitelist I mentioned [above](https://github.com/Hoohm/CITE-seq-Count/issues/5#issuecomment-402858989).

**Comment by bio-la** [comment]
thanks @wflynny , i don't know why it was unclear to me that the indexes of the hashing library were the same as a normal 10x, just a separate sample. I think I know what to expect now.

**Comment by oursu-broad** [comment]
thanks @wflynny!

**Comment by Hoohm** [comment]
Hello @wflynny  and @bio-la 
The new version is out.
Can you please test it out. Let me know how it works for you.
Regex is now optional and it can deal with tags of different lengths.

**Comment by bio-la** [comment]
@Hoohm @wflynny Hi there, just tested the new version of the script. didn't specify the tag regex as per suggestion (do only if you know what you're doing! nice one:) )
I think I should now use the results to classify the barcode depending on the proportion of reads mapping to the Antibody oligo, and define doublets those with no clear dominant proportion?

**Comment by bio-la** [comment]
sorry, obviously found this https://satijalab.org/seurat/hashing_vignette.html 
i was just trying to reinvent the wheel.

**Comment by Hoohm** [comment]
This might come up later but not here. This is "just" CITE-seq-count.
I'm going to bo adding CITE-seq-count to dropSeqPipe and there I will add this feature.

**Comment by Janosch22** [comment]
@Hoohm Hi, I'm just about to try the CITE-seq-count tool for a non-CITEseq hashing experiment.
In our study the reads look different from normal CITE-seq reads. It can be that the read starts with some
random bases before the actually barcode occurs. Can CITE-seq-count manage that or does it assume that the first base in the read is also the first base of the barcode? 

I'd be grateful for some advice

all the best

Jan

**Comment by Hoohm** [comment]
@Janosch22 normally not. You could simply trim the first few bases and then run it as usual, but it doesn't handle indels, only mismatches for now.

**Comment by tprkp** [comment]
Hi @Hoohm , Thanks for the script! I am just running my first dataset through the script and would like to know the definition of "bad_struct" and "no_match" in the results file. What qualifies a read to go into those counts? 
Kind regards,
Ting

**Comment by Hoohm** [comment]
Hi @bio-la
Bad_struct was more of a test for the beginning of the protocol to see if those tags were actually there. The first versions had a polyA tail which we checked for. Reads that didn't have those would get flagged as bad struct.

no_match is a "good" struct but that doesn't fit to any given tag sequences. This could be because the number of mutations/sequencing errors is higher than the given hamming distance threshold.

Hope this clears it up. I'll get to some documentation when I have some spare time to give a bit more details on the outputs.

**Comment by tprkp** [comment]
Hi @Hoohm , Thanks for the quick response. I see, so a count in the bad_struct column has no poly A? I'm trying to work out what proportion of the ADT reads are actually carry overs of cDNA reads from when the two libraries were separated in SPRI size selection. 
As an aside, I'm also finding that while the script is mostly running perfectly, a couple of the runs yielded a results table that only consists of bad_struct, no_match and total_reads rows. Does this mean that absolutely no reads aligned to any of the antibody barcodes? 

Thanks for your help!
Ting

**Comment by Hoohm** [comment]
The bad struct could also come from a constant sequence that is present in all of your tags but is not found in read2. It depends a lot on the dataset and the chemistry.

This flag is actually not present in the latest version as it was confusing and not very useful for standard users. Which version are you running?

**Comment by Hoohm** [comment]
I'm closing this now.
Feel free to reopen it if necessary.
