### ISSUE TITLE
Running CITEseqCount on cDNA Fastq files

### ISSUE THREAD

**Issue by apf2139** [Hoohm/CITE-seq-Count#51]
Hello,

Thank you for developing this tool! I've received some hashed data from a collaborator and I have been trying to use it to no avail - it seems to run properly, but the report yaml shows percent unmapped = 100%.

After doing some reading I realized that my situation may in fact be similar to the problem faced in issue  #5 , where I only actually have FASTQ files for the cDNA libraries while a typical hashed dataset actually has its own Adt fastq files. I have only a single pair of files, R1 and R2; I am actually able to find the HTO sequences in R2 using grep (several thousand in R2 compared to a few dozen in R1). In that thread, someone suggested the following strategy:

1.  Running the cDNA fastq files (in this case only R1 and R2) through Cellranger Count.
2. Running R1 and R2 through Cite-Seq Count, perhaps using as a whitelist the cells identified by cellranger count. The author of that post suggested specifying some number of A's in the regex option, which I could not find any reference to in the documentation.

Is there any advice you can provide for this scenario? Thank you very much in advance!

**Comment by Hoohm** [comment]
Hello @apf2139 

I would suggest running the data as is with a whitelist if you have one, even before cellranger.
This would allow capturing of cells from the HTO data even if they weren't found by the RNA.

The ploy A in the regex is not possible anymore since the option is deprecated.
It's odd that you don't get any mapping though.
Could you show some HTO barcodes and maybe a grep of it in R2?

**Comment by apf2139** [comment]
Hi, thanks for your quick response.

Can you clarify what you mean by HTO barcodes?
Here are the HTO sequences I have:
ACCCACCAGTAAGAC,Hash1
GGTCGAGAGCATTCA,Hash2
CTTGCCGCATGTCAT,Hash3
AAAGCATTCTTCACG,Hash4
CTTTGTCTTTGTGAG,Hash5

Attached is a text file with 5 reads matching HTO number 1 in one of the R2 files.
[grepr2.txt](https://github.com/Hoohm/CITE-seq-Count/files/3061066/grepr2.txt)

Thanks a lot for your help.

**Comment by Hoohm** [comment]
Hello @apf2139,

any news regarding your run?

**Comment by apf2139** [comment]
For anyone reading:

The program does indeed run! Even though run_report.yaml can show "0% unmapped", the output files should still be checked and samples can to some degree be demultiplexed, for example through Seurat. However, trying to find the HTOs in the cDNA fastq files will have low sensivity, ie, many cells will appear to be negative, so generating separate sequencing data for the HTOs is still a good idea if you can do so.

Thanks @Hoohm !
