### ISSUE TITLE
CITE-seq COUNT cell number

### ISSUE THREAD

**Issue by notimenocall** [Hoohm/CITE-seq-Count#52]
Hi,
I am using CITE-seq COUNT for ADT and HTO analysis and couldn't get the correct number of cells defined. (And it worked before but not anymore...)
Below is the script used:
```
CITE-seq-Count -R1 ADT_HTO_tag_R1.fastq.gz -R2 ADT_HTO_tag_R2.fastq.gz -t /home/chenx302/Xiao/XC7_hashing/XC7_libraries_tag_CITE.csv -cbf 1 -cbl 16 -umif 17
-umil 28 -cells 11496 -wl /home/chenx302/Xiao/XC7_hashing/XC7_WHITELIST_antibody -o ~/Xiao/XC7_hashing/XC7_hashing/outs/fastq_path/tags_fastqs/CITE_SEQ_04122
019
```
The WHITELIST contains 11496 rows and I also '-cells 11496'. However the barcodes.tsv in umi_count only contains 11484 rows.
Any idea why?? I got the proper number of rows before with the same files. But now I merged all the *R1*.fastq from different NextSeq lanes and the same for *R2*.fastq and it stopped working. Can CITE-seq COUNT handle multiple R1 R2 entries? I did the below script previously but it seems like the output from the last file overwrite the previous.
```
R1="ADT_tag_S2_L001_R1_001.fastq.gz ADT_tag_S2_L004_R1_001.fastq.gz HTO_tag_S3_L003_R1_001.fastq.gz ADT_tag_S2_L002_R1_001.fastq.gz HTO_tag_S3_L001_R1_001.f
astq.gz HTO_tag_S3_L004_R1_001.fastq.gz ADT_tag_S2_L003_R1_001.fastq.gz HTO_tag_S3_L002_R1_001.fastq.gz"

R2="ADT_tag_S2_L001_R2_001.fastq.gz ADT_tag_S2_L004_R2_001.fastq.gz HTO_tag_S3_L003_R2_001.fastq.gz ADT_tag_S2_L002_R2_001.fastq.gz HTO_tag_S3_L001_R2_001.f
astq.gz HTO_tag_S3_L004_R2_001.fastq.gz ADT_tag_S2_L003_R2_001.fastq.gz HTO_tag_S3_L002_R2_001.fastq.gz"

arr=($R1)
arr2=($R2)

for i in {0..7}
do
       CITE-seq-Count -R1 ${arr[i]} -R2 ${arr2[i]} -t /home/chenx302/Xiao/XC7_hashing/XC7_libraries_tag_CITE.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -cells 114
96 -wl /home/chenx302/Xiao/XC7_hashing/XC7_WHITELIST_antibody -o ~/Xiao/XC7_hashing/XC7_hashing/outs/fastq_path/tags_fastqs/CITE_SEQ
done
```

**Comment by Hoohm** [comment]
Hello @notimenocall 

Could you check if the report gives you a value of 12 for the field "uncorrected_cells"?

Also, can you tell me which version you're using vs the one before?

**Comment by notimenocall** [comment]
Hi @Hoohm ,

Yes.
```
Running time: 27.0 minutes, 33.09 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 55054608
Percentage mapped: 96
Percentage unmapped: 4
Uncorrected cells: 12
Correction:
        Cell barcodes collapsing threshold: 1
        Cell barcodes corrected: 175408
        UMI collapsing threshold: 2
        UMIs corrected: 665030
Run parameters:
        Read1_filename: ADT_HTO_tag_R1.fastq.gz
        Read2_filename: ADT_HTO_tag_R2.fastq.gz
        Cell barcode:
                First position: 1
                Last position: 16
        UMI barcode:
                First position: 17
                Last position: 28
        Expected cells: 11496
        Tags max errors: 2
        Start trim: 0
```

**Comment by notimenocall** [comment]
How to correct for this please?

**Comment by Hoohm** [comment]
There is no error here. The 12 cells that are uncorrected are aggregated cells and should be filtered out. If you still want the uncorrected UMI counts for them you can get them in the `uncorrected_cells` folder as `dense_umis.tsv`

Version 1.4.3 added this to fix the long hanging of the UMI correction. If you get a TAG/HTO/ADT in one cells with over 20'000 different UMIs, this cell won't be corrected.

It might change in the future.

**Comment by notimenocall** [comment]
The umi_count could not be added as a seurat assay object if the cell numbers are not identical correct? How would you recommend doing it in this case?

**Comment by Hoohm** [comment]
I would subset the original seurat object and get rid of the uncorrected cells. Then add the assay as usual.

**Comment by notimenocall** [comment]
Thanks a lot. Really appreciate it!
