### ISSUE TITLE
Can't run CITEseq count

### ISSUE THREAD

**Issue by ibseq** [Hoohm/CITE-seq-Count#54]
Hi, 
I've installed citeseq count correctly and run the command but I'm getting this error;
I am using the data from the original paper:

CITE-seq-Count -R1 SRR8281061_1.fastq.gz -R2 SRR8281061_2.fastq.gz -t TAG_LIST.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 3000 -wl whitelist.xlsx -o cell_hashing_paper
Traceback (most recent call last):
  File "/anaconda3/bin/CITE-seq-Count", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 240, in main
    collapsing_threshold=args.bc_threshold)
  File "/anaconda3/lib/python3.6/site-packages/cite_seq_count/preprocessing.py", line 70, in parse_whitelist_csv
    whitelist = [row[0].strip(STRIP_CHARS) for row in csv_reader
  File "/anaconda3/lib/python3.6/site-packages/cite_seq_count/preprocessing.py", line 70, in <listcomp>
    whitelist = [row[0].strip(STRIP_CHARS) for row in csv_reader
  File "/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

thanks :)

[whitelist.xlsx](https://github.com/Hoohm/CITE-seq-Count/files/3117923/whitelist.xlsx)

[TAG_LIST.xlsx](https://github.com/Hoohm/CITE-seq-Count/files/3117926/TAG_LIST.xlsx)

**Comment by ibseq** [comment]
just realised I shouldn't have used the whitelist from the 10x website...but that shouldn't be the issue

**Comment by ibseq** [comment]
the two files were suppided to be in csv ...my mistake. 
I re-run it and got this, despite changing 10x barcode and UMIN lenghts:
any help?

CITE-seq-Count -R1 SRR8281061_1.fastq.gz -R2 SRR8281061_2.fastq.gz -t TAG_LIST.csv -cbf 1 -cbl 15 -umif 16 -umil 26 -cells 27000 -wl whitelist.csv -o cell_hashing_paper
Testing cell barcode collapsing threshold of 1
Using 1 for cell barcode collapsing threshold
[ERROR] Read1 length is shorter than the option you are using for Cell and UMI barcodes length. Please, check your options and rerun.

Exiting the application.

**Comment by Hoohm** [comment]
Hello @ibseq,

this means that the start and stop of the cell barcode + UMI  parameters you use are longer than the sequences in R1.
Double check the cell barcode length as well as the UMI length and rerun with the correct parameters.

**Comment by Hoohm** [comment]
Hello @ibseq,

have you been able to run this properly?

**Comment by ibseq** [comment]
Dear Patrick 
thanks for following up with this. 
I didn’t have chance to look into citeseq as I have been focusing on other aspects of the analysis. 
As soon as I go back using it I shall let you know

bw
irene

**Comment by Hoohm** [comment]
Closing this for now. Feel free to reopen if you have updates regarding this issue.

**Comment by ibseq** [comment]
yep - sorted!
