### ISSUE TITLE
Error message when running multiple lane read files

### ISSUE THREAD

**Issue by YunZheHuang** [Hoohm/CITE-seq-Count#58]
Hello, 

I have total 8 files (L1-L4) for both read 1 and read 2 , while I put those files in  read 1 and read 2 (8 total) into the script it throw out an error saying "CITE-seq-Count: error: unrecognized arguments:" . I think Cite-seq-count should be able to support multiple read files, right? 

My command is 

CITE-seq-Count  -R1 L1-R1.fastq.gz L2-R1.fastq.gz L3-R1.fastq.gz L4-R1.fastq.gz -R2 L1-R2.fastq.gz L2-R2.fastq.gz L3-R2.fastq.gz L4-R2.fastq.gz -t Antibodytag.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 6121 -o output 

I saw someone online saying that CITE-seq-Count don't support multiple lane files and I have to merged them all into one file for each read before feeding into the program, is that true?

**Comment by Hoohm** [comment]
Hello  @YunZheHuang 

You are right, CITE-seq-Count doesn't support multilane for now but I see how this could be helpful especially if you're working with 10x data.

For now, you have to cat all R1 and R2 separately.

I'll keep this in mind for next version!

**Comment by YunZheHuang** [comment]
Hello @Hoohm 

Thank you so much for your response! I did cat all the files from each read, however, another error threw out saying " [ERROR] Sequence length in R2_merged.fastq.gz is not consistent. Please, trim all sequences at the same length.", since my raw data is untrimmed, why this error happen? Thank you !

**Comment by Hoohm** [comment]
My guess is that you mixed some R1 and some R2 files together. CITE-seq-Count check read length on both R1 and R2. If you all reads are no the same length in R1 or in R2, you will get this error message.

**Comment by YunZheHuang** [comment]
@Hoohm 

I double checked my concatenation and I promised that I didn't mix R1 and R2

**Comment by Hoohm** [comment]
Did you do any trimming on either of them?

**Comment by YunZheHuang** [comment]
@Hoohm 
no I didn't.

**Comment by Hoohm** [comment]
can you run that on your file?
`zcat test_R1.fastq.gz | awk '{if(NR%4==2) print $0}' | awk '{ print length }' | uniq`

replace my test_R1.fastq.gz by your concatenated files

**Comment by YunZheHuang** [comment]
@Hoohm 

There is a bunch of number 
98
97
98
97
98
97
98
97
98
`
Like this

**Comment by Hoohm** [comment]
So, 9 lanes? With different reading depths of 97 and 98 for some reason.
Could you trim the R2 file at 97? This will fix the issue.

**Comment by YunZheHuang** [comment]
@Hoohm 

Not just 9 lanes, there are bunch of them I just post a small section. Actually it's not only 97 and 98, it also have 96. So if I do a trimming, what tool do you recommend?

**Comment by Hoohm** [comment]
I'd advise [cutadapt](https://cutadapt.readthedocs.io/en/stable/guide.html#shortening-reads-to-a-fixed-length)

**Comment by YunZheHuang** [comment]
@Hoohm 

Ok. Thanks! Let me trim my file and then see if it works!

**Comment by YunZheHuang** [comment]
@Hoohm 

I finished trimming and run the script again, this time the script stop in the middle and the error message is below:

`Correcting cell barcodes
Finding a whitelist
/anaconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
  lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
Traceback (most recent call last):
  File "/anaconda3/bin/CITE-seq-Count", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 352, in main
    collapsing_threshold=args.bc_threshold)
  File "/anaconda3/lib/python3.7/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
    plotfile_prefix=False)
  File "/anaconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
    cell_barcode_counts, cell_number, plotfile_prefix)
  File "/anaconda3/lib/python3.7/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
    raise ValueError("Something's gone wrong here!!")
ValueError: Something's gone wrong here!!`

Can you please tell me how to resolve this problem? Thanks!

**Comment by Hoohm** [comment]
Hello @YunZheHuang ,
this bug is fixed on the develop branch.
I'm gonna release a new version soon and it will also support multiple lanes runs.

**Comment by Hoohm** [comment]
Should be fixed in the new 1.4.3 release.
The new version also handles multiple lanes now.
Closing this.
