### ISSUE TITLE
AttributeError: 'int' object has no attribute 'values' (v1.4.2-dev)

### ISSUE THREAD

**Issue by heathergeiger** [Hoohm/CITE-seq-Count#59]
Ran CITE-Seq-Count like so to count HTOs for a cell hashing project.

``
citeseqcount -cells 30000 -R1 /path/to/sample.R1.fastq.gz -R2 /path/to/sample.R2.fastq.gz -t HTO_sequence_vs_sample_ID.csv -cbf 1 -cbl 16 -umif 17 -umil 28 -o
/path/to/Sample_sample/analysis
``
Ran as an SGE job. Here are the messages in standard output:

Counting number of reads
Started mapping
Processing 39,955,851 reads
CITE-seq-Count is running with 56 cores.
Mapping done for process 85683. Processed 713,497 reads
Mapping done for process 85684. Processed 713,497 reads
..
Mapping done for process 85738. Processed 713,516 reads
Mapping done
Merging results
Counter()
Looking for a whitelist
Collapsing cell barcodes
Correcting umis

And standard error:

Traceback (most recent call last):
  File "/nfs/sw/citeseqcount/citeseqcount-1.4.2-dev/python/bin/citeseqcount", line 11, in <module>
    load_entry_point('CITE-seq-Count==1.4.3', 'console_scripts', 'CITE-seq-Count')()
  File "/nfs/sw/citeseqcount/citeseqcount-1.4.2-dev/python/lib/python3.7/site-packages/CITE_seq_Count-1.4.3-py3.7.egg/cite_seq_count/__main__.py", line 477, in main
  File "/nfs/sw/citeseqcount/citeseqcount-1.4.2-dev/python/lib/python3.7/site-packages/CITE_seq_Count-1.4.3-py3.7.egg/cite_seq_count/__main__.py", line 169, in create_report
AttributeError: 'int' object has no attribute 'values'

Any idea what might have gone wrong? 

We have been running the development version of the program, after previously experiencing the same issue listed in issue #48 (https://github.com/Hoohm/CITE-seq-Count/issues/48) and you recommended switching to that. We have run several other samples using the development version over the past two weeks or so without any issues.

So unless you have added some additional changes to development version of the script since May 21 (when we updated to development version), I don't think that will solve the problem.

**Comment by Hoohm** [comment]
Hello @heathergeiger 

I've noticed that the dev branch is currently not working as intended due to tests I've been running on improving long whitelist performance.

Since #48 is linked to a small bug, I think I should be able to make a hotfix for this specifically.

I'm going to work on CITE-seq-Count this week, I'll keep you updated when I have some news for your issue.

**Comment by Hoohm** [comment]
Can you try out the dev branch now? I've reverted to a previous commit that should help you out.

**Comment by Hoohm** [comment]
Hello @heathergeiger,
I expect this was fixed as I hoped. Feel free to reopen if not.
