### ISSUE TITLE
UMI  or cell-barcodes with a hamming distance

### ISSUE THREAD

**Issue by Tim0thy1** [Hoohm/CITE-seq-Count#6]
Hi,Hoohm

Does CITE-seq-Count collapse UMI  or cell-barcodes with a hamming distance of N?

**Comment by Hoohm** [comment]
Hi @Tim0thy1 
It collapses TAG sequences of a hamming distance of N.
Cell and UMI barcodes are only collapsed on exact match.

**Comment by Tim0thy1** [comment]
Could you explain to why  Cell and UMI barcodes are only collapsed on perfect match? Because I found 
① UMIs within edit distance = 1 are merged together  in Drop­seq core computational protocol 
② Cellbarcode within 1 mismatch away from the  cellbarcode whitelist  is then corrected in  cellranger software training

thx.

**Comment by Hoohm** [comment]
Hello,
One reason is that the signal of tags is stronger/clearer than mrna making
the potential overinflation less if a problem.

The barcode collapsing would add a few counts but i expect the impact to be
very low. In terms of UMI collapsing it might result on a bit of over
inflation of counts if the sequencing quality is poor.

 It could be implemented though. I'll check if it's easy to add or not.

Does it answer your question?

**Comment by Tim0thy1** [comment]
Thanks for you answer.  
If you have finished adding that fuction ,please let   me know.
