### ISSUE TITLE
pysam issues with cite-seq-count 1.4.2

### ISSUE THREAD

**Issue by yuchchen** [Hoohm/CITE-seq-Count#60]
I previously used CITE-seq-Count 1.3.2 for data processing. It worked fine. However, when I tried to upgrade to CITE-seq-Count 1.4.2, one required toolkit "pysam" could not be installed on my computer.

When I installed pysam 0.15, it generated an error "ERROR: Command "python setup.py egg_info" failed with error code 1." While this error was reported in some posts on Internet, the proposed solutions on-line didn't work for me. Can you advise how to overcome this?

My computer uses Windows OS. I tried pysam 0.15.0, 0.15.1, and 0.15.2.  I tried both Python 3.6 and 3.7, and I have updated pip and setuptools. 

Thanks again.

**Comment by Hoohm** [comment]
Hello @yuchchen 

I need a few more pieces of information about your system.

- Do you use conda/miniconda?
- Could you paste the whole error when you try to install the package as well as the command line used?
- Are you sure that pip is using python3.6 when it installs packages? I'm asking because it seems that some people have the same issue as you but only with python3.7

**Comment by yuchchen** [comment]
Hi,

1. I tried both Anaconda and also Command Prompt directly.

2. Full error message is attached below.

3. I installed Python 3.6 and 3.7 in two different folders. I executed
install command in their respective folders. I think pip used python 3.6
and 3.7 respectively. Is there another way to check it.

Thanks much.

Sincerely,
Yu-Chih

python -m pip install --upgrade pysam
Collecting pysam
  Using cached
https://files.pythonhosted.org/packages/15/f6/ce0611aaa1865a616f7dc164fbf046eaf38f2b17c6d404403c56250beb93/pysam-0.15.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    make: ./version.sh: Command not found
    make: ./version.sh: Command not found
    make: uname: Command not found
    Makefile:228: Extraneous text after `else' directive
    Makefile:231: Extraneous text after `else' directive
    Makefile:231: *** only one `else' per conditional.  Stop.
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"C:\Users\YU-CHI~1\AppData\Local\Temp\pip-install-tejjupf8\pysam\setup.py",
line 223, in <module>
        htslib_make_options = run_make_print_config()
      File
"C:\Users\YU-CHI~1\AppData\Local\Temp\pip-install-tejjupf8\pysam\setup.py",
line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Users\Yu-Chih
Chen\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 356,
in check_output
        **kwargs).stdout
      File "C:\Users\Yu-Chih
Chen\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 438,
in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']'
returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in
C:\Users\YU-CHI~1\AppData\Local\Temp\pip-install-tejjupf8\pysam\

**Comment by Hoohm** [comment]
Well this is going to be fun :)

[https://github.com/pysam-developers/pysam/issues/740](https://github.com/pysam-developers/pysam/issues/740)

One of the [solutions](https://github.com/pysam-developers/pysam/issues/575) seems to use bash in windows.

**Comment by yuchchen** [comment]
If there is no other way to solve it, trying Ubuntu maybe an alternative.

Thanks much.

Yu-Chih

**Comment by Hoohm** [comment]
Yeah I guess it's linked to pysam's installer and they haven't answered this issues since November 2018. My guess is, they won't bother. :(

**Comment by yuchchen** [comment]
Hi, Patrick,

I have another question regarding CITE-seq-Count. I used DropSeq toolkit to
generate DGE file. One option is to use DetectBeadSynthesisErrors to
correct truncated cell barcodes. After correction, it may generate an "N"
as the final bit of the corrected cell barcode. My question is whether
CITE-seq-Count can handle "N" properly. For example, can an ADT with
"AAAAAAAAAAAA" cell barcode be mapped to "AAAAAAAAAAAN"?

Thanks much.

Sincerely,
Yu-Chih

**Comment by Hoohm** [comment]
UMI-tools is used to correct for cell barcodes and if I'm not mistaken, it's letter agnostic.

However, if you provide a whitelist with Ns in it, CITE-seq-Count will complain.

If it's only the last letter of the cell barcode. You can change the position of the `-cbl` to one bit earlier and provide a whitelist with one less cell barcode base.

Let me know if it's confusing :)

**Comment by yuchchen** [comment]
That makes sense. Thanks much.

Yu-Chih

**Comment by yuchchen** [comment]
Hi, Patrick,

I installed Ubuntu, and it seems to work.

After computation, I got a output folder. However, the data format is quite
complicated. Is there an easy to generate a TSV file as in 1.3 version?
Hope to have column 1 as the cell barcode, and ADT counts in the following
columns.

Thanks much.

Sincerely,
Yu-Chih


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by yuchchen** [comment]
--dense seems to work. Thanks.

Yu-Chih


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Hoohm** [comment]
Great!
Happy that it worked in the end.

There is some help in the documentation if you want to use the sparse matrices: https://hoohm.github.io/CITE-seq-Count/Reading-the-output/

Can I close this issue?

**Comment by yuchchen** [comment]
Sure. Please. Thanks.

Yu-Chih
