### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by jshrivastava** [Hoohm/CITE-seq-Count#64]
@Hoohm  Cannot install even with python3.6. When I give command
sudo -H pip3 install CITE-seq-Count==1.4.2 --no-cache-dir

I am getting the error: RuntimeError: Python version >= 3.5 required.

when I checked python version -python -V
It gives me Python 3.6.3.

Please suggest.

**Comment by Hoohm** [comment]
Hello @jshrivastava 
I'm going through all the issues and I just saw I never answered yours. Sorry for that.
Did you manage to solve your issue?
I expect you might have multiple python versions installed.
