### ISSUE TITLE
How to check how many Antibody read are used? 

### ISSUE THREAD

**Issue by YunZheHuang** [Hoohm/CITE-seq-Count#65]
Hello,

Is that there is a way that I can check how many Antibody read being used in the running of CITE-seq-Count? I run my sample with the cellranger pipeline and there is only a small fraction of Antibody read were used. I just want to check if this also happen in CITE-Seq-Count. I checked the CITE-Seq-Count report but couldn't find this information. Can you please tell me if there is a way that I can find this information? Thank you!

**Comment by Hoohm** [comment]
Hello @YunZheHuang 

I'm not sure I follow what you exactly need.
One information that might help you is the percentage mapped and unmapped in the report.

If that is not enough, could you maybe try to rephrase your question in a different way?

**Comment by YunZheHuang** [comment]
Hello @Hoohm 

Thank you so much for your response. 

I'm using another pipeline that developed by Cellranger, they generate a report showing that for my sample  the fraction of Antibody that is usable is 39%, this means the fraction of reads that contain a recognized antibody barcode, a valid UMI, and a cell-associated barcode for my sample is only 39%. I'm surprise with this, want to see if CITE-seq-count also provide this information. If CITE-seq-count also provide this information, that would help a lot. In the CITE-seq-Count report, it shows that 96% of the reads are mapped, are you saying that this is corresponding to the fraction of usable antibody in Cellranger pipeline?

**Comment by Hoohm** [comment]
To my knowledge, cell ranger uses mRNA data to filter cells as valid or not.

The report from CSC gives you 96% of total antibody reads being mapped.

it is possible that cell ranger tells you that 39% of your reads are attributed to cells that pass the filter criteria. Does this make sense?

CSC does not filter anything so you will get all the possible cells, even the ones that have surface markers but not enough genes recovered.

**Comment by Hoohm** [comment]
Hello @YunZheHuang 
any news regarind this issue?

**Comment by YichaoOU** [comment]
Hello, 

Does this 39% mean good quality or very bad quality?

Thanks,
Yichao
