### ISSUE TITLE
[ERROR] Read1 length is shorter

### ISSUE THREAD

**Issue by jmosullivan** [Hoohm/CITE-seq-Count#66]
Hi, 

I am obtaining this error when running CITE-SEQ-COUNT 

[ERROR] Read1 length is shorter than the option you are using for Cell and UMI barcodes length. Please, check your options and rerun. 

My barcodes are 12-bp length
UMI 8-bp length

I have checked R1.gz for the 12-bp barcodes and they are contained in these fq files

The following I am running which would be correct but is generating the above error messge:

CITE-seq-Count -T 4 -R1 R1.gz -R2 R2.gz -t tags.txt -cbf 1 -cbl 12 -umif 13 -umil 20 -cells 264 -wl whitelist.tsv -o samples_adt.out

Any suggestions would be great!

Thank you

Jennifer

**Comment by Hoohm** [comment]
Hello @jmosullivan and please forgive me the late response.

This is really strange. Can you double-check that your sequencing was done as expected?
Did you by any chance to some filtering prior to running CSC?

**Comment by Hoohm** [comment]
Closing this. Feel free to reopen if you have updates regarding this issue.
