### ISSUE TITLE
Error when running CITE Seq on my 10X fastq files

### ISSUE THREAD

**Issue by bioInfo25** [Hoohm/CITE-seq-Count#67]
So I am running CITE Seq on some 10X fastq files and get the following error:

`[ERROR] Sequence length in R2.fastq.gz is not consistent. Please, trim all sequences at the same length.
Exiting the application.`

From my understanding of the error does this data need to be trimmed first for the R2 paired end read file and then run using Cite-seq-count??

Because I was under the impression this tool takes in the raw fastq.gz reads.

Let me know. Thanks.

**Comment by Hoohm** [comment]
Hello @bioInfo25 

This means that some R2 reads are longer than others. Did any quality trimming happen beforehand?

**Comment by Hoohm** [comment]
Hello @bioInfo25,
I never got a response from you. Could you solve the issue?

**Comment by Hoohm** [comment]
Closing this for now, feel free to reopen.
