### ISSUE TITLE
CreatSeuratObject goes wrong for merged data

### ISSUE THREAD

**Issue by happar73** [Hoohm/CITE-seq-Count#68]
I use the seurat to merge 3 ctrl and 3 stim data separately, and want to do the integrating stimulated vs. control datasets to learn cell-type specific response (shttps://satijalab.org/seurat/v3.0/immune_alignment.html)

The code for merging the data is as follow. It works smoothly.

```
#load 3 veh data#
setwd("C:/Users/ASUS/Desktop")
VEH1.data <-Read10X(data.dir = "m_VEH_7d_2_VEH2_mex")
VEH1<- CreateSeuratObject(counts = VEH1.data, project = "VEH1")
VEH1
VEH2.data <-Read10X(data.dir = "m_VEH_7d_3_VEH3_mex")
VEH2<- CreateSeuratObject(counts = VEH2.data, project = "VEH2")
VEH2
VEH3.data <-Read10X(data.dir = "m_VEH_7d_4_VEH4_mex")
VEH3<- CreateSeuratObject(counts = VEH3.data, project = "VEH3")
VEH3

#merge 3 veh data#
VEH.big <- merge(VEH1, y = c(VEH2, VEH3), add.cell.ids = c("1", "2", "3"), project = "VEH6")
VEH.big
View(VEH.big)
```
After the merge, I want to read the integrated data to do the integrating analysis, but I got an error to creat the Seurat Object.

![image](https://user-images.githubusercontent.com/50378244/61335083-10a15700-a7e1-11e9-8081-3758a259b890.png)

Can you guys give me a solution to run the merged data or creat the object?

Thank you very much!

**Comment by Hoohm** [comment]
Hello @happar73 
Normally your VEH.big should already be the merged seurat object. What class is VEH.big?

**Comment by happar73** [comment]
> Hello @happar73
> Normally your VEH.big should already be the merged seurat object. What class is VEH.big?

**Comment by happar73** [comment]
> Hello @happar73
> Normally your VEH.big should already be the merged seurat object. What class is VEH.big?

Yes, you are right. It is a object already. Thanks very much!
