### ISSUE TITLE
top unknown barcodes now reports full-length read?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#70]
Hello,

We switched to 1.4.2 relatively recently, but I cant say exactly when this change occurred.  Cite-seq-Count supports a -u argument, which causes the tool to output the top unknown barcodes.  At least when that feature was added, I believe it output only the first 25bp of the read (assuming this is the length of the barcode it expected).  However, as of 1.4.2 this appears to be outputting the full length read (our input is non-trimmed reads of ~150bp).  

This itself is a minor issue.  however, I am posting this b/c I'm curious whether the fact we're giving it FL reads is sub-optimal is other ways we're not seeing?  For example, are various internal codepaths trying to cluster or error correct using the entire 150bp, instead of just the actual barcode part?  

If the tool 'knows' what read length to expect, would you consider making trimming to the expected length an automatic part of reading the FASTQs?

Thanks,
Ben

**Comment by Hoohm** [comment]
Hello @bbimber 
the internal code is using the length of the TAG provided in the TAGs file. The trimming is done during the alignment process. The reads that don't align are then saved full length and flagged as unmapped. Mapped reads are not stored, I just store the UMI.

I'd rather keep the whole length for the output. The main reason being that if you have an adapter issue that shifts your reads, you might not see that if you cut the read at the length of the TAG.

Hope this helps.

**Comment by bbimber** [comment]
OK, seems totally fine to me.  just wanted to be sure it was parsing our data as expected.

**Comment by Hoohm** [comment]
Great, I'll close this one then.
