### ISSUE TITLE
typo: no_umi_correctio instead of no_umi_correction

### ISSUE THREAD

**Issue by ChristophH** [Hoohm/CITE-seq-Count#72]
If I'm reading this correctly commit https://github.com/Hoohm/CITE-seq-Count/commit/88aa6647b4c770c8a75ea76f7a9b37160efc0f5a introduced a typo and changed the command line argument from `--no_umi_correction` to `no_umi_correctio`

**Comment by Hoohm** [comment]
Hey @ChristophH,
thanks for the catch!
I'll add the change in the next release :)
