### ISSUE TITLE
Count on 5' libraries gives all cells ummapped

### ISSUE THREAD

**Issue by manugarciaquismondo** [Hoohm/CITE-seq-Count#73]
Greetings,

When @Adeebius and I run CITE-seq-Count (v 1.4.2) on a 5' library with the following parameters:
```
CITE-seq-Count -R1 <Route to R1 Fastq GZ file>
                                -R2 <Route to R2 Fastq GZ file>
                                -t  <Route to Tag file>
                                -cbf 1
                                -cbl 16
                                -umif 17
                                -umil 28
                                -cells 1000000
                                --max-error 1
                                -o <Output directory>

```
The file _run_report.yaml_ yields that the percentage of unmapped cells is 100%:

```
Date: 2019-08-20
Running time: 18.0 minutes, 0.8353 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 10775807
Percentage mapped: 0
Percentage unmapped: 100
Uncorrected cells: 10
Correction:
        Cell barcodes collapsing threshold: 1
        Cell barcodes corrected: 0
        UMI collapsing threshold: 2
        UMIs corrected: 1206489
Run parameters:
        Read1_filename: <Route to R1 Fastq GZ file>
        Read2_filename: <Route to R2 Fastq GZ file>
        Cell barcode:
                First position: 1
                Last position: 16
        UMI barcode:
                First position: 17
                Last position: 28
        Expected cells: 1000000
        Tags max errors: 1
        Start trim: 0
```

However, when we run CITE-seq-Count for a 3' sample, the percentage of ummapped cells drops to 8%.

Can you please advise on what parameters we should adjust so that we can obtain a lower percentage of unmapped cells for 5' samples?

Thank you,

**Comment by Hoohm** [comment]
Hello @manugarciaquismondo 

I would need a few reads to look at them and check out how the structure is. Could you send me 10'000 reads?

**Comment by manugarciaquismondo** [comment]
Thank you for your e-mail. If I enable `--sliding-window` the count is done properly; I think that this issue can be now closed.

**Comment by Hoohm** [comment]
Ok. Maybe there is a sequence before the actual tag. The sliding window would catch that but you could also find a fixed length to trim from the start with the `--start-trim` option.

I'm closing it then.
Best wishes
