### ISSUE TITLE
How can I get the right IDtags

### ISSUE THREAD

**Issue by happar73** [Hoohm/CITE-seq-Count#78]
Hi CITE-seq-Count team,

I am a novice in CITE-seq-Count. When I ran the test data, it works. But when I ran my own data, I found I don't know how to get the right IDtags and the whitelists.

Does the IDtags mean the antibody sequencing? like this webpage: https://www.biolegend.com/en-us/totalseq. CD4: AACAAGACCCTTGAG?

Can I use the whitelists for all the cells? Display in the 10x webpages: https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-

I tried these and got the wrong matrix.mtx.

The output is like this:

> Date: 2019-09-15
> Running time: 21.0 hours, 57.0 minutes, 38.96 seconds
> CITE-seq-Count Version: 1.4.2
> Reads processed: 48330610
> Percentage mapped: 97
> Percentage unmapped: 3
> Uncorrected cells: 0
> Correction:
> 	Cell barcodes collapsing threshold: 1
> 	Cell barcodes corrected: 0
> 	UMI collapsing threshold: 2
> 	UMIs corrected: 0
> Run parameters:
> 	Read1_filename: /home/jbclab/Desktop/19006FL-01-02-02_S105_L003_R1_001.fastq.gz
> 	Read2_filename: /home/jbclab/Desktop/19006FL-01-02-02_S105_L003_R2_001.fastq.gz
> 	Cell barcode:
> 		First position: 1
> 		Last position: 16
> 	UMI barcode:
> 		First position: 17
> 		Last position: 26
> 	Expected cells: 0
> 	Tags max errors: 2
> 	Start trim: 0

Thanks for you help.

Best,
Yale

**Comment by Hoohm** [comment]
Hello @happar73 

I think I know what you are struggling with but I need some infos to confirm.

What kind of run is this? 10x v2, 10x v3?

To answer your first question, yes, ID tags are the tags that are linked to the antibody you are using.

For the cell barcode whitelist I'll need you to tell me what the base chemistry is.

**Comment by happar73** [comment]
We use the 10x v3.

**Comment by happar73** [comment]
Thanks @Hoohm,
We use the 10x v3.

**Comment by Hoohm** [comment]
Great, thank you.

The one you tried using is the V2, so I'm not surprised you got nothing in the output.

V3 chemistry has a catch to it. There is a mapping between RNA barcodes and Protein barcodes. that can be found on cellrangers [github](https://github.com/10XGenomics/cellranger/blob/master/lib/python/cellranger/barcodes/translation/3M-february-2018.txt.gz)

On top of that, the whitelist provided on github is around 6M barcodes but the chemistry only has 3M barcodes. That's why, for now, i would not advise using a whitelist for V3.

Let me know how that works

**Comment by Hoohm** [comment]
Hello @happar73,
I've added a new page in the documentation to explain this issue with V3 for future users.
Could you manage to run it?

**Comment by happar73** [comment]
@Hoohm Sorry for the late reply, and thanks very much for your help. I have run it successfully. 

[Running time: 13.0 hours, 15.0 minutes, 32.69 seconds
CITE-seq-Count Version: 1.4.2
Reads processed: 48330610
Percentage mapped: 97
Percentage unmapped: 3
Uncorrected cells: 0
Correction:
	Cell barcodes collapsing threshold: 1
	Cell barcodes corrected: 128766
	UMI collapsing threshold: 2
	UMIs corrected: 7935276
Run parameters:
	Read1_filename: /19006FL-01-02-02_S105_L003_R1_001.fastq.gz
	Read2_filename: /19006FL-01-02-02_S105_L003_R2_001.fastq.gz
	Cell barcode:
		First position: 1
		Last position: 16
	UMI barcode:
		First position: 17
		Last position: 26
	Expected cells: 0
	Tags max errors: 2
	Start trim: 0](url)

Thanks again!

**Comment by Hoohm** [comment]
Great! I'm closing this then :)
