### ISSUE TITLE
Value Error! 

### ISSUE THREAD

**Issue by hothri** [Hoohm/CITE-seq-Count#80]

**Comment by hothri** [comment]
Hi 
I am working on the 10x hashtag data from  https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM2895283, subset  https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP127179 

While running this data I am getting a following error after processing certain amount of reads. 
What could be the reason for this error?

```
/data/WHRI-GenomeCentre/CITE_seq_tool/cite_env/lib/python3.6/site-packages/umi_tools/whitelist_methods.py:283: RuntimeWarning: invalid value encountered in sqrt
  lineVecNorm = lineVec / np.sqrt(np.sum(lineVec**2))
Mapping done
Merging results
Correcting cell barcodes
Finding a whitelist
Traceback (most recent call last):
  File "/CITE_seq_tool/cite_env/bin/CITE-seq-Count", line 10, in <module>
    sys.exit(main())
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 352, in main
    collapsing_threshold=args.bc_threshold)
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/cite_seq_count/processing.py", line 310, in correct_cells
    plotfile_prefix=False)
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/umi_tools/whitelist_methods.py", line 447, in getCellWhitelist
    cell_barcode_counts, cell_number, plotfile_prefix)
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/umi_tools/whitelist_methods.py", line 322, in getKneeEstimateDistance
    raise ValueError("Something's gone wrong here!!")
ValueError: Something's gone wrong here!!

```

**Comment by cassieminlele** [comment]
I'm also working on 10x V3 hashtag single-cell data. Total cell number is 14000. when I run cite seq count, after 5h or 6h running,  I also the same error. 

> Counting number of reads
Started mapping
Processing 257,748,582 reads
CITE-seq-Count is running with 24 cores.

line:NTATTGCGTTATCTGGTCGTATGGTGCAGGTCGAGAGCATTCAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAATGAAAAAAACGACCAGATAAAACAATAAAAATAGGAAAAGAGTGGT
cell_barcode:NTATTGCGTTATCTGG   UMI:b'TCGTATGGTG'       TAG_seq:GGTCGAGAGCATTCAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAATGAAAAAAACGACCAGATAAAACAATAAAAATAGGAAAAGAGTGGT
line length:119 cell barcode length:16  UMI length:10   TAG sequence length:91
Best match is: hashtag2-GGTCGAGAGCATTCA
.....................
Mapping done for process 3651. Processed 10,739,530 reads
Mapping done
Merging results
Correcting cell barcodes
Finding a whitelist
............................
ValueError: Something's gone wrong here!!

**Comment by Hoohm** [comment]
Hello @hothri  and @cassieminlele 
Could you please test out the develop branch, It should fix your issue.

**Comment by hothri** [comment]
@Hoohm 
Hi the develop version worked fine. Thank you
