### ISSUE TITLE
Sequence saturation UMI index & barcode rank features

### ISSUE THREAD

**Issue by danmoore1987** [Hoohm/CITE-seq-Count#81]
Hi @Hoohm ,
Thank you again for the easy to use package!

Just a suggested enhancement feature that i think a lot of people might be interested in. Would be cool if in the CITE count report workflow you also generate a barcode rank and UMI saturation index plots/csv! :)

**Comment by Hoohm** [comment]
Hello @danmoore1987,
why not, would you have any specific example to link here so that I can take a look?

**Comment by danmoore1987** [comment]
Hi @Hoohm,
Thanks for the reply!

Essentially some of the cell ranger outputs. So one to measure per barcode, how many UMI's were assigned.
<img width="400" alt="gex-barcode-rank-plot" src="https://user-images.githubusercontent.com/45685480/66626482-225d9380-ec44-11e9-90b8-6a0875dd06ce.png">

The second is this. Its so we know if we need to sequence the CITE library deeper.
![Capture_saturation index](https://user-images.githubusercontent.com/45685480/66626816-5d13fb80-ec45-11e9-9ee2-69b1d713be3e.JPG)

Cell ranger uses this formula for it:
Sequencing Saturation = 1 - (n_deduped_reads / n_reads)
where:
n_deduped_reads = Number of unique (valid cell-barcode, valid UMI, gene) combinations among confidently mapped reads. 
n_reads = Total number of confidently mapped, valid cell-barcode, valid UMI reads.

Cheers!

**Comment by bbimber** [comment]
Just want to echo: this would be quite useful to know. we're actively trying to sort out whether some of our lesser libraries would benefit from more sequence depth.

I believe the run_report gives data to calculate saturation, at least globally, right? I think it would be valid to use 'Reads processed' as n_reads (we could adjust by percentage mapped?), and 'UMIs corrected' as n_deduped_reads, correct? 

The per-cell plot above is informative. Presumably one could read/merge the 'read_count' folder and 'umi_count' folders to accomplish this, right?

**Comment by bbimber** [comment]
I need to sanity check the data, but this is derived from combining umi_count and read_count folders:

![image](https://user-images.githubusercontent.com/7724863/102014008-9001c580-3d08-11eb-915e-9723936be279.png)

the R code is here: https://github.com/BimberLab/cellhashR/blob/2211878b792d7c0c5ff48e4183cdcd7a44dec8b8/R/Preprocessing.R#L278

**Comment by danmoore1987** [comment]
This is great @bbimber ! 

I also noticed your cellhashR package for post-processing QC of libraries. Can't wait to give it a go! :)

**Comment by bbimber** [comment]
@danmoore1987 yes, i'm still surprised there arent more tools that exist that do what we're trying in cellhashR. we'd welcome any feedback. part of my goal is cellhashR is to specifically compare across different calling algorithms, since we find some do better or worse with different inputs.

With respect to saturation in particular, it would be great if you could confirm the tool is giving you believable values. I was surprised how non-saturated our libraries often were, but this wasnt something I had been tracking.

**Comment by Hoohm** [comment]
Ok, folks, I'm on holiday!!!

Let me take a look since I'm gonna work on this damn 1.5 release!!!

I'll keep you posted :)

Thanks for the code!

**Comment by bbimber** [comment]
@Hoohm No worries - I actually think we implemented this in cellhashR; however, I'd love to figure out features that make this work synergistically with Cite-Seq-Count.

**Comment by Hoohm** [comment]
Yes! That would be amazing. Can you send me an email so we can have a quick chat these days maybe?

**Comment by Hoohm** [comment]
Ok, so 1.5.0 is nearly finished. Running some tests on datasets to see how it matches the older version.

For your specific needs here is a non exhaustive list of changes that affects your code:

* MTX format has changed. First column is now the TAG sequence, second column feature name. This means that `Read10X` runs by default onthe right column (gene.colunm=2)
* UMI MTX counts as well as the dense matrix have dropped the unmapped feature.
* For technologies such as 10x v3 who posses two different barcodes for each cell when running mRNA and protein data, youcan now provide the translation reference. First column, cell barcode in the mRNA data, second column cell barcode in the protein data. The MTX outputs will have two columns in the barcodes.tsv file, first, default will be the mRNA column, second will be the Protein data.

I think these are the only ones affecting your code, but I might be missing something. Let me know :)

**Comment by bbimber** [comment]
@Hoohm is there a heuristic code can perform to determine what format of input it's getting? for example, if we have a function for processCiteSeqCount(outputFolder), can this code automatically figure out what format it was passed?

**Comment by Hoohm** [comment]
Not sure which format you are referring to.

If you are talking about the translated version, then yes, the barcodes.tsv
will hold two columns instead of two.

**Comment by bbimber** [comment]
Maybe I misunderstood, but in your prior post didnt you say the MTX format is changing in version 1.5.0? Ideally, I would like cellhashR::ProcessCountMatrix() to just work with either the output from Cite-Seq-Count 1.5.0 or prior versions. I suppose I could read the matrix into memory with gene.column=1, test for the presence of 'unmapped', and if it's not present re-read using gene.column=2?

**Comment by Hoohm** [comment]
It's not changing that much.

I would really love to have a chat on zoom with you, would be interesting
to have a back and forth about this since I'm not completely fixed on
everything.

**Comment by bbimber** [comment]
sure - would be happy to. i didnt realize you worked at 10x until I googled your name just now.  my email is bimber@ohsu.edu

**Comment by Hoohm** [comment]
Closing this for now.
