### ISSUE TITLE
pip doesnt contain 1.4.3?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#88]
hello,

when I try to install from pip, the latest version it detects is 1.4.2.  i'm not that familiar with how the python repos work - would you anticipate that it simply takes time for all repos to contain your latest version?  it appears pip lets you install direct from github - would you recommend that?

thanks,
ben

**Comment by Hoohm** [comment]
Hello  @bbimber 
this is strange. I just uninstalled mine and reinstalled from pip and got 1.4.3
Which python version do you have?

**Comment by bbimber** [comment]
Ah - I had 3.5.1.  I remade the virtualenv with 3.6 and it seems to be working.  Thanks

**Comment by Hoohm** [comment]
Great, closing this.
