### ISSUE TITLE
can not install the new version 1.4.3

### ISSUE THREAD

**Issue by zt-qi** [Hoohm/CITE-seq-Count#91]
Hello, I have a problem of installing the new version 1.4.3
I tried the following commands but both gave errors. Could you please advise? Thanks a lot!
pip3 install CITE-seq-Count==1.4.3
pip install CITE-seq-Count==1.4.3
ERROR: Could not find a version that satisfies the requirement CITE-seq-Count==1.4.3 (from versions: 1.2, 1.3, 1.3.1a0, 1.3.1, 1.3.2)
ERROR: No matching distribution found for CITE-seq-Count==1.4.3

**Comment by joeytai2010** [comment]
I found the same error with you. Could you please let me know how to fix the issue? Thanks.

Joey

**Comment by Hoohm** [comment]
Hello @joeytai2010 
This is related to you python and/or pip installation.

You need to have at least python3.6

**Comment by joeytai2010** [comment]
Thanks for your reply. I have figured the issue.

Zhiyu
