### ISSUE TITLE
CITE-seq-Count package not found on Amazon AWS

### ISSUE THREAD

**Issue by YunZheHuang** [Hoohm/CITE-seq-Count#94]
I'm trying to run CITE-seq-Count on AWS but when I tried to install it using sudo yum install in Amazon Linux 2 AMI is said "package not found". Can anyone tell me how can I install it to my AWS?

**Comment by Hoohm** [comment]
Hello @YunZheHuang 

could you paste the exact command you are trying to run please.
To install CSC you should run `pip install CITE-seq_count=1.4.3`

**Comment by akornberg** [comment]
I've been having issues too. This is what I get from that command:

ERROR: Could not find a version that satisfies the requirement CITE-seq_count==1.4.3 (from versions: 1.2)
ERROR: No matching distribution found for CITE-seq_count==1.4.3

**Comment by Hoohm** [comment]
You might need to install python 3.6 before trying to install CSC

**Comment by akornberg** [comment]
When I type in python3 --version I get:

Python 3.8.0 (or on AWS I get Python 3.6.8)

So presumably that is the most updated version? When I use pip install on AWS or on my laptop I will get these below (sorry for the block of text). I'm guessing it is trying to install with python 2.7 and not 3.8 or 3.68. Is there a way to specify which python to use?

_DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support_

and

_ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iBFGhQ/python-levenshtein/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iBFGhQ/python-levenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i7Cq8g --python-tag cp27
       cwd: /tmp/pip-install-iBFGhQ/python-levenshtein/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/Levenshtein
  copying Levenshtein/__init__.py -> build/lib.linux-x86_64-2.7/Levenshtein
  copying Levenshtein/StringMatcher.py -> build/lib.linux-x86_64-2.7/Levenshtein
  running egg_info
  writing requirements to python_Levenshtein.egg-info/requires.txt
  writing python_Levenshtein.egg-info/PKG-INFO
  writing namespace_packages to python_Levenshtein.egg-info/namespace_packages.txt
  writing top-level names to python_Levenshtein.egg-info/top_level.txt
  writing dependency_links to python_Levenshtein.egg-info/dependency_links.txt
  writing entry points to python_Levenshtein.egg-info/entry_points.txt
  reading manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*pyc' found anywhere in distribution
  warning: no previously-included files matching '*so' found anywhere in distribution
  warning: no previously-included files matching '.project' found anywhere in distribution
  warning: no previously-included files matching '.pydevproject' found anywhere in distribution
  writing manifest file 'python_Levenshtein.egg-info/SOURCES.txt'
  copying Levenshtein/_levenshtein.c -> build/lib.linux-x86_64-2.7/Levenshtein
  copying Levenshtein/_levenshtein.h -> build/lib.linux-x86_64-2.7/Levenshtein
  running build_ext
  building 'Levenshtein._levenshtein' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/Levenshtein
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-2.7/Levenshtein/_levenshtein.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-levenshtein_

**Comment by Hoohm** [comment]
@YunZheHuang maybe rolling back to python 3.6 or 3.7 might help here. Not sure
