### ISSUE TITLE
Multiple Lanes and Trimming Sequences

### ISSUE THREAD

**Issue by akornberg** [Hoohm/CITE-seq-Count#97]
Hi @Hoohm and @arkal , thank you all for the great work it has been really helpful for our lab! 

We had a sequencing run of AdT/HTOs on multiple lanes (1-4). I tried merging the fastq files with the cat function and while running: 

```
CITE-seq-Count 
-R1 ./adt_read1/merged_adt_S2_L005_R1_001.fastq.gz 
-R2 ./adt_read2/merged_adt_S2_L005_R2_001.fastq.gz ... (tags, cells, etc).
```
and I recieve the error: Sequence length in ./adt_read2/merged_adt_S2_L005_R2_001.fastq.gz is not consistent. Please, trim all sequences at the same length. Exiting the application.

I see that in 1.4.3 version of CITE-seq-Count there is the possibility to use multiple lanes (and not merge the .fastq.gz files) but when I try to run 

```
CITE-seq-Count
-R1 ./adt_read1/ADT703_S2_L001_R1_001.fastq.gz , ./adt_read1/ADT703_S2_L002_R1_001.fastq.gz , ./adt_read1/ADT703_S2_L003_R1_001.fastq.gz , ./adt_read1/ADT703_S2_L004_R1_001.fastq.gz 

-R2 ./adt_read2/ADT703_S2_L001_R2_001.fastq.gz , ./adt_read2/ADT703_S2_L002_R2_001.fastq.gz , ./adt_read2/ADT703_S2_L003_R2_001.fastq.gz , ./adt_read2/ADT703_S2_L004_R2_001.fastq.gz 
```
I receive an error saying those arguments are unused. Is there a way to incorporate all lanes L001-4 into one run? Thank you for the help, as you can probably guess I'm somewhat new at this.

**Comment by Hoohm** [comment]
Hello @akornberg 
might it be that the spaces are causing this error? Try without spaces between the commas and the lanes

**Comment by akornberg** [comment]
Thank you @Hoohm, that allows all the fastq.gz files all to be recognized. Now I've ended up with a similar error to the one I'd seen before. 

```
[ERROR] Sequence length in adt_read2/ADT703_S2_L001_R2_001.fastq.gz is not consistent. Please, trim all sequences at the same length.
Exiting the application.
```
This data is untrimmed, I downloaded FASTQs directly from Illumina basespace so a bit unsure as to why this comes up still. Any ideas?

**Comment by Hoohm** [comment]
Sometimes Illumina trims the data depending on the options that are used to demultiplex.

Can you check with fastqc?

**Comment by akornberg** [comment]
Went into the read 2 fastq file, the read length ranges from 26 (just a few at the start) to 40-42 (vast majority of sequences). We really only want the first 12 nucleotide reads, so I tried to trim using seqtk to take just the first 12 nucleotides but that caused an unequal number of read1 and read2 files, preventing CITE-seq-Counts from running. 

Looking at it with fastqc the sequence length does vary but I'm not sure where to find where/if Ilumina trimmed the data in fastqc.

**Comment by arkal** [comment]
`bcl2fastq` has the ability to trim/mask adapters and chances are, whoever processed the bcls used the trim option. I would suggest looking into [fastp](https://github.com/OpenGene/fastp) to do what you were trying with seqtk. You can use the following flags:
-A (disable adapter trimming)
-B 12 (Make sure R2 is only 12bp at max)
-G
-l 12 (Reads must be 12bp minimum) 
and possibly more too (look at the readme)

I've been using fastp a lot these days and i highly recommend it.

**Comment by Hoohm** [comment]
Maybe I can change that restriction to run even if the length is different.
I think it comes back to string slices when the mapping is done.

Knowing that all reads in R2 are long enough helps not checking the length each time, reducing processing time.

I'm checking if it's ok to change it and let people run uneven R2 reads.

**Comment by akornberg** [comment]
For this I just used the FASTQs generated on illumina basespace, no processing before. When we have run these on Miseq with just one lane this has not been a problem. I will explore the new trimming with fastp! 

If we could run with uneven R2 reads that would be great too (even with the extended time)!

**Comment by akornberg** [comment]
Hi again!

Using fastp and trimming all the sequences worked. The program takes quite a bit of time (2-3 hours for 7000 cells) but it does work in the end.
