### ISSUE TITLE
Raw counts

### ISSUE THREAD

**Issue by marianaql** [Hoohm/CITE-seq-Count#98]
Hello, is there any way I can get the raw counts? I understand that the output only contains filtered counts. Thank you!

**Comment by Hoohm** [comment]
@marianaql would you define raw counts?
There is not much filtering going on.

**Comment by marianaql** [comment]
I am trying to use the total UMI of a cell barcode to rank the barcodes to plot it on a log scale (from highest to lowest) (Rank barcode plot from raw counts). 
I define the raw counts as the equivalent of raw_feature_bc_matrix in CellRanger. Raw counts contain every barcode from fixed list of known-good barcode sequences. This includes background and non-cellular barcodes.
In other words "The difference between the raw and the filtered gene matrices is that the raw matrices contain all cell barcodes and the filtered dataset only contains cell barcodes that Cell Ranger considers to be real, i.e. droplets that contain a cell. ".

**Comment by Hoohm** [comment]
One way to get more than the provided whitelist is to ask for a certain number of cells, preferably, more than you expect to have with the `--cells` argument.

**Comment by Hoohm** [comment]
I'm assuming that you managed what you needed. Please reopen the issue if needed.
