### ISSUE TITLE
Large integer error, possibly being ignored?

### ISSUE THREAD

**Issue by bbimber** [Hoohm/CITE-seq-Count#99]
Hello,

We're running cite-seq-count 1.4.2 multithreaded on somewhat large FASTA inputs.  We see errors like below during these jobs.  despite the error the job seems to continue to completion.  is this an actual problem, or is cite-seq-count somehow compensating for the failed workers?  

We emailed about this issue before, i think.  I can increase the # of cores (presumably fewer reads/worker?) and avoid the error.  however, in general we want to be submitting cluster jobs with the fewest required cores.  If this is an error that is just being ignored as cite-seq-count progresses, this seems like a problem.  if it's not an actual concern, then it would be slightly nicer if there was a little better error reporting.

21 Nov 2019 09:20:30,260 DEBUG:     Processed 1,000,000 reads in 13.32 seconds. Total reads: 33,000,000 in child 41411
21 Nov 2019 09:20:43,499 DEBUG:     Processed 1,000,000 reads in 13.24 seconds. Total reads: 34,000,000 in child 41411
21 Nov 2019 09:20:56,411 DEBUG:     Processed 1,000,000 reads in 12.91 seconds. Total reads: 35,000,000 in child 41411
21 Nov 2019 09:21:02,038 DEBUG:     Mapping done for process 41411. Processed 35,433,839 reads
21 Nov 2019 09:21:39,361 DEBUG:     Process ForkPoolWorker-5:
21 Nov 2019 09:21:39,397 DEBUG:     Traceback (most recent call last):
21 Nov 2019 09:21:39,406 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/pool.py", line 125, in worker
21 Nov 2019 09:21:39,416 DEBUG:         put((job, i, result))
21 Nov 2019 09:21:39,423 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
21 Nov 2019 09:21:39,433 DEBUG:         self._writer.send_bytes(obj)
21 Nov 2019 09:21:39,442 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
21 Nov 2019 09:21:39,453 DEBUG:         self._send_bytes(m[offset:offset + size])
21 Nov 2019 09:21:39,458 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/connection.py", line 396, in _send_bytes
21 Nov 2019 09:21:39,469 DEBUG:         header = struct.pack("!i", n)
21 Nov 2019 09:21:39,476 DEBUG:     struct.error: 'i' format requires -2147483648 <= number <= 2147483647
21 Nov 2019 09:21:39,484 DEBUG:     
21 Nov 2019 09:21:39,494 DEBUG:     During handling of the above exception, another exception occurred:
21 Nov 2019 09:21:39,509 DEBUG:     
21 Nov 2019 09:21:39,522 DEBUG:     Traceback (most recent call last):
21 Nov 2019 09:21:39,544 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
21 Nov 2019 09:21:39,561 DEBUG:         self.run()
21 Nov 2019 09:21:39,574 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
21 Nov 2019 09:21:39,587 DEBUG:         self._target(*self._args, **self._kwargs)
21 Nov 2019 09:21:39,601 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/pool.py", line 130, in worker
21 Nov 2019 09:21:39,610 DEBUG:         put((job, i, (False, wrapped)))
21 Nov 2019 09:21:39,618 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
21 Nov 2019 09:21:39,626 DEBUG:         self._writer.send_bytes(obj)
21 Nov 2019 09:21:39,632 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
21 Nov 2019 09:21:39,639 DEBUG:         self._send_bytes(m[offset:offset + size])
21 Nov 2019 09:21:39,645 DEBUG:       File "/home/groups/prime-seq/pipeline_tools/bin/primeseq-python/lib/python3.6/site-packages/multiprocess/connection.py", line 396, in _send_bytes
21 Nov 2019 09:21:39,653 DEBUG:         header = struct.pack("!i", n)
21 Nov 2019 09:21:39,662 DEBUG:     struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by Hoohm** [comment]
I'm seeing this more and more with the samples increasing in read numbers. I don't have a quick fix for now, I recommend not concatenating fastqs as well as use a bit mores cores to run the data. It should help out while I actually get a real fix.

**Comment by bbimber** [comment]
OK. Do you know whether this results in loss of information? If one thread hits this error are those reads omitted from the end product?

**Comment by Hoohm** [comment]
I'm amazed that it simply crash to be honest... I would be afraid of data loss for sure yes.

**Comment by Hoohm** [comment]
@bbimber 
I'm trying a new way of dealing with large datasets on [this branch](https://github.com/Hoohm/CITE-seq-Count/tree/feature/namedtuples).
Could you try it out?

**Comment by Hoohm** [comment]
Hello @bbimber 
the latest develop branch now has a new way of dealing with reads and chunking them.
There is a hard limit on how many reads are passed per chunk.
Can you check if you still get the same error?
